#!/usr/bin/env bash

# ------------------------
#
# Description
# ---
# Build instances
# Calling without argument with build all INSTANCES
# Defined in package.json workspaces
#
# ------------------------

if [ -z $1 ]; then
  # get the INSTANCES from package.json workspaces
  INSTANCES=$(
    PKG=$(cat package.json)
    node -pe 'JSON.parse(process.argv[1]).workspaces.packages.join(" ")' "$PKG"
  )
else
  INSTANCES="instances/$1"
fi

# ---- Loop INSTANCES ----
CURRENT_DIRECTORY=$PWD
for FOLDER in $INSTANCES
do
  if [[ "$FOLDER" =~ ^instances/.* ]]; then
    cd $FOLDER
    yarn build
    cd $CURRENT_DIRECTORY
  fi
done

exit 0
