#! /bin/bash

APP=$1

DSFR_FILES=(utility/utility.min.css dsfr.min.css fonts/ icons/)

OUTPUT_FOLDER="$PWD/public"
INPUT_FOLDER=../../node_modules/@gouvfr/dsfr/dist

# Check DSFR INPUT_FOLDER
if [ ! -d "$INPUT_FOLDER" ]; then
  echo "ERROR : Missing @gouvfr/dsfr input folder"
  exit 1
fi

# Check OUTPUT_FOLDER
if [ ! -d "$OUTPUT_FOLDER" ]; then
  echo "ERROR : Missing public output folder"
  exit 1
fi

echo "INFO : Copying DSFR sources to $APP public folder"

for FILE in "${DSFR_FILES[@]}"; do
  SRC="$INPUT_FOLDER/$FILE"
  DEST="$OUTPUT_FOLDER/dsfr/$FILE"
  mkdir -p $(dirname "$DEST")
  cp -r "$SRC" "$DEST"
done

exit
