export enum FieldTypes {
  TEXT = 'text',
  DATE = 'date',
  EMAIL = 'email',
  RADIO = 'radio',
  NUMBER = 'number',
  HIDDEN = 'hidden',
  SELECT = 'select',
  TEXTAREA = 'textarea',
  CHECKBOX = 'checkbox',

  /* not yet implemented */
  // TEL = 'tel',
  // URL = 'url',
  // WEEK = 'week',
  // FILE = 'file',
  // TIME = 'time',
  // RANGE = 'range',
  // COLOR = 'color',
  // IMAGE = 'image',
  // MONTH = 'month',
  // SEARCH = 'search',
  // PASSWORD = 'password',
  // DATETIME_LOCAL = 'datetime-local',
}
