// == FI
const fip = {
  // -- FIP - FIP1-LOW - Activated - no discov
  "FIP1-LOW": {
    uid: "fip1-low",
    name: "fip1-low",
    active: true,
    display: true,
    isBeta: false,
    title: "IDP1 - LOW",
    image: "fi-mock-faible.svg",
    imageFocus: "fi-mock-faible.svg",
    alt: "fip1-low",
    trustedIdentity: false,
    eidas: 1,
    mailto: "",
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    specificText: "specific text fip1-low",
    url: "https://fip1-low.docker.dev-franceconnect.fr",
    tokenURL: "https://fip1-low.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip1-low.docker.dev-franceconnect.fr/userinfo",
    authzURL: "https://fip1-low.docker.dev-franceconnect.fr/authorize",
    endSessionURL: "https://fip1-low.docker.dev-franceconnect.fr/session/end",
    discovery: false,
    clientID: "myclientidforfip1-low",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 1,
    createdAt: new Date("2022-02-15 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    response_types: ["code"],
    id_token_signed_response_alg: "HS256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "HS256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    redirect_uris: [
      "https://core-fcp-low.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fcp-low.docker.dev-franceconnect.fr/api/v2/client/logout-callback",
    ],
  },
  // -- FIP - FIP2-LOW - Activated
  "FIP2-LOW": {
    uid: "fip2-low",
    name: "fip2-low",
    active: true,
    display: true,
    isBeta: false,
    title: "IDP2 - LOW",
    image: "fi-mock-faible.svg",
    imageFocus: "fi-mock-faible.svg",
    alt: "fip2-low",
    trustedIdentity: false,
    eidas: 1,
    mailto: "",
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    specificText: "specific text fip2-low",
    url: "https://fip2-low.docker.dev-franceconnect.fr",
    discoveryUrl:
      "https://fip2-low.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    discovery: true,
    clientID: "myclientidforfip2-low",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 2,
    createdAt: new Date("2022-02-20 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    response_types: ["code"],
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    // fip2-low using old oidc-callback route
    redirect_uris: [
      "https://core-fcp-low.docker.dev-franceconnect.fr/api/v2/oidc-callback/fip2-low",
    ],
    post_logout_redirect_uris: [
      "https://core-fcp-low.docker.dev-franceconnect.fr/api/v2/client/logout-callback",
    ],
  },
  // -- FIP - FIP3-LOW - Activated
  "FIP3-LOW": {
    uid: "fip3-low",
    name: "fip3-low",
    active: true,
    display: true,
    isBeta: false,
    title: "IDP3 - LOW",
    image: "fi-mock-faible.svg",
    imageFocus: "fi-mock-faible.svg",
    alt: "fip3-low",
    trustedIdentity: false,
    eidas: 1,
    mailto: "",
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    specificText: "specific text fip3-low",
    url: "https://fip3-low.docker.dev-franceconnect.fr",
    discoveryUrl:
      "https://fip3-low.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    discovery: true,
    clientID: "myclientidforfip3-low",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 3,
    createdAt: new Date("2022-02-25 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    response_types: ["code"],
    id_token_signed_response_alg: "RS256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "RS256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    redirect_uris: [
      "https://core-fcp-low.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fcp-low.docker.dev-franceconnect.fr/api/v2/client/logout-callback",
    ],
  },
  // -- FIP - FIP4-LOW - Beta
  "FIP4-LOW": {
    uid: "fip4-low",
    name: "fip4-low",
    active: true,
    display: true,
    isBeta: true,
    title: "IDP4 - Identity Provider - eIDAS substantiel",
    image: "fi-mock-substantiel.svg",
    imageFocus: "fi-mock-substantiel.svg",
    alt: "fip4-low",
    trustedIdentity: false,
    eidas: 2,
    mailto: "",
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    specificText: "specific text fip4-low",
    url: "https://fip4-low.docker.dev-franceconnect.fr",
    discoveryUrl:
      "https://fip4-low.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    discovery: true,
    clientID: "myclientidforfip4-low",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 4,
    createdAt: new Date("2022-02-25 17:09:17"),
    updatedAt: new Date("2022-02-25 17:09:17"),
    updatedBy: "admin",
    response_types: ["code"],
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    redirect_uris: [
      "https://core-fcp-low.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fcp-low.docker.dev-franceconnect.fr/api/v2/client/logout-callback",
    ],
  },
  // -- FIP - FIP5-LOW - Disabled
  "FIP5-LOW": {
    uid: "fip5-low",
    name: "fip5-low",
    active: false,
    display: true,
    isBeta: false,
    title: "IDP5 - LOW disabled",
    image: "fi-mock-faible.svg",
    imageFocus: "fi-mock-faible.svg",
    alt: "fip5-low",
    trustedIdentity: false,
    eidas: 1,
    mailto: "",
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    specificText: "specific text fip5-low",
    url: "https://fip5-low.docker.dev-franceconnect.fr",
    discoveryUrl:
      "https://fip5-low.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    discovery: true,
    clientID: "myclientidforfip5-low",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 1,
    createdAt: new Date("2022-02-15 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    response_types: ["code"],
    id_token_signed_response_alg: "HS256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "HS256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    redirect_uris: [
      "https://core-fcp-low.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fcp-low.docker.dev-franceconnect.fr/api/v2/client/logout-callback",
    ],
  },
  // -- FIP - FIP6-LOW - Invisible
  "FIP6-LOW": {
    uid: "fip6-low",
    name: "fip6-low",
    active: true,
    display: false,
    isBeta: false,
    title: "IDP6 - LOW invisible",
    image: "fi-mock-faible.svg",
    imageFocus: "fi-mock-faible.svg",
    alt: "fip6-low",
    trustedIdentity: false,
    eidas: 1,
    mailto: "",
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    specificText: "specific text fip6-low",
    url: "https://fip6-low.docker.dev-franceconnect.fr",
    discoveryUrl:
      "https://fip6-low.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    discovery: true,
    clientID: "myclientidforfip6-low",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 1,
    createdAt: new Date("2022-02-15 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    response_types: ["code"],
    id_token_signed_response_alg: "HS256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "HS256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    redirect_uris: [
      "https://core-fcp-low.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fcp-low.docker.dev-franceconnect.fr/api/v2/client/logout-callback",
    ],
  },
  // -- FIP - FIP7-LOW - Disabled and Invisible
  "fip7-LOW": {
    uid: "fip7-low",
    name: "fip7-low",
    active: false,
    display: false,
    isBeta: false,
    title: "IDP7 - LOW disabled and invisible",
    image: "fi-mock-faible.svg",
    imageFocus: "fi-mock-faible.svg",
    alt: "fip7-low",
    trustedIdentity: false,
    eidas: 1,
    mailto: "",
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    specificText: "specific text fip7-low",
    url: "https://fip7-low.docker.dev-franceconnect.fr",
    discoveryUrl:
      "https://fip7-low.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    discovery: true,
    clientID: "myclientidforfip7-low",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 1,
    createdAt: new Date("2022-02-15 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    response_types: ["code"],
    id_token_signed_response_alg: "HS256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "HS256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    redirect_uris: [
      "https://core-fcp-low.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fcp-low.docker.dev-franceconnect.fr/api/v2/client/logout-callback",
    ],
  },
  // -- FIP - FIP8-LOW - Activated - whitelisted by fsp4
  "FIP8-LOW": {
    uid: "fip8-low",
    name: "fip8-low",
    active: true,
    display: true,
    isBeta: false,
    title: "IDP8 - LOW",
    image: "fi-mock-faible.svg",
    imageFocus: "fi-mock-faible.svg",
    alt: "fip8-low",
    trustedIdentity: false,
    eidas: 1,
    mailto: "",
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    specificText: "specific text fip8-low",
    url: "https://fip8-low.docker.dev-franceconnect.fr",
    discoveryUrl:
      "https://fip8-low.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    discovery: true,
    clientID: "myclientidforfip8-low",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 1,
    createdAt: new Date("2022-02-15 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    response_types: ["code"],
    id_token_signed_response_alg: "HS256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "HS256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    redirect_uris: [
      "https://core-fcp-low.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fcp-low.docker.dev-franceconnect.fr/api/v2/client/logout-callback",
    ],
  },
  // -- FIP - FIP9-LOW - Activated - no endSessionUrl
  "FIP9-LOW": {
    uid: "fip9-low",
    name: "fip9-low",
    active: true,
    display: true,
    isBeta: false,
    title: "IDP9 - LOW - no endSessionUrl",
    image: "fi-mock-faible.svg",
    imageFocus: "fi-mock-faible.svg",
    alt: "fip9-low",
    trustedIdentity: false,
    eidas: 1,
    mailto: "",
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    specificText: "specific text fip9-low",
    url: "https://fip9-low.docker.dev-franceconnect.fr",
    tokenURL: "https://fip9-low.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip9-low.docker.dev-franceconnect.fr/userinfo",
    endSessionURL: "",
    authzURL: "https://fip9-low.docker.dev-franceconnect.fr/authorize",
    discovery: false,
    clientID: "myclientidforfip9-low",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 1,
    createdAt: new Date("2022-02-15 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    response_types: ["code"],
    id_token_signed_response_alg: "HS256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "HS256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    redirect_uris: [
      "https://core-fcp-low.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fcp-low.docker.dev-franceconnect.fr/api/v2/client/logout-callback",
    ],
  },
};

// -- FIs ----------

Object.values(fip).forEach((fi) => {
  print(`FIP > Initializing provider: ${fi.name} - Activated`);
  db.provider.update({ uid: fi.uid }, fi, { upsert: true });
});
