// == FS
const spLegacy = {
  fsp1: {
    name: "Service Provider Example",
    site: "https://fsp1.com",
    redirect_uris: [
      "https://fsp1.docker.dev-franceconnect.fr/login-callback",
      "https://fsp1.docker.dev-franceconnect.fr/data-callback",
      "https://fsp1.docker.dev-franceconnect.fr/tracks-callback",
    ],
    post_logout_redirect_uris: [
      "https://fsp1.docker.dev-franceconnect.fr/logout-callback",
    ],
    key: "a0cd64372db6ecf39c317c0c74ce90f02d8ad7d510ce054883b759d666a996bc",
    client_secret:
      "tbjUBu7gwf317yIjPRlo7zk89LAPOUzWhDzodO1sh0jAqudu6BxI37NqkzGdR8DfHT9mgt6+ZgpLZ8OU8HZHT/OXRcZrssIbpYzoiale4dEmYOnDmBcwbwJhzjQ=",
    credentialsFlow: false,
    email: "fsp1@franceconnect.loc",
    logo: "logo_Mairie de Paris_1280px-Mairie_De_Paris.svg.png",
    IPServerAddressesAndRanges: ["1.1.1.1"],
    active: true,
    type: "public",
    __v: 4,
    updatedAt: "2019-04-24 17:09:17",
    updatedBy: "admin",
    scopes: [
      "openid",
      "given_name",
      "family_name",
      "birthdate",
      "idp_birthdate",
      "gender",
      "birthplace",
      "birthcountry",
      "email",
      "preferred_username",
      "address",
      "phone",
      "idp_id",
      "dgfip_rfr",
      "dgfip_nbpart",
      "dgfip_sitfam",
      "dgfip_pac",
      "dgfip_aft",
      "cnam_paiements_ij",
      "connexion_tracks",
    ],
    identityConsent: false,
    trustedIdentity: false,
    eidas: 1,
    platform: "CORE_LEGACY",
    rep_scope: [],
  },

  fsp2: {
    name: "Virtual Private Service Provider for Scopes",
    site: "https://site.com",
    redirect_uris: [
      "https://fsp2.docker.dev-franceconnect.fr/login-callback",
      "https://fsp2.docker.dev-franceconnect.fr/data-callback",
      "https://fsp2.docker.dev-franceconnect.fr/tracks-callback",
    ],
    post_logout_redirect_uris: [
      "https://fsp2.docker.dev-franceconnect.fr/logout-callback",
    ],
    key: "8279ce2e262b86324c004afee58ae2d63814baa20ed983696f2245c1f4d7e7fb",
    client_secret:
      "bbg3e0zidcMLRFF7MPOUIgyOYQo2fkVR7xYLtLAEUiWGQBcXhg8X0/+K0ZXGipk/Cr4oZTYqL5MRN4y5v16MUFjFnvGffCzrn3M3w2voQhDzq8Ggj/gorS1hYhY=",
    credentialsFlow: false,
    email: "fsp2@franceconnect.loc",
    logo: "logo_Mairie de Paris_1280px-Mairie_De_Paris.svg.png",
    IPServerAddressesAndRanges: ["2.2.2.2"],
    active: true,
    type: "private",
    __v: 4,
    updatedAt: "2019-04-24 17:09:17",
    updatedBy: "admin",
    blacklistByIdentityProviderActivated: true,
    blacklistByIdentityProvider: {
      "fip2-low": true,
    },
    scopes: [
      "openid",
      "given_name",
      "family_name",
      "birthdate",
      "gender",
      "birthplace",
      "birthcountry",
      "dgfip_rfr",
      "dgfip_nbpart",
      "dgfip_sitfam",
      "dgfip_pac",
      "dgfip_aft",
      "cnam_paiements_ij",
      "connexion_tracks",
    ],
    identityConsent: false,
    trustedIdentity: false,
    eidas: 1,
    platform: "CORE_LEGACY",
    rep_scope: [
      "Papier-Citoyenneté-Elections",
      "Famille-Scolarité",
      "Social-Santé",
      "Travail-Formation",
    ],
  },

  fsp3: {
    name: "Virtual Private Service Provider for Consent",
    site: "https://site.com",
    redirect_uris: [
      "https://fsp3.docker.dev-franceconnect.fr/login-callback",
      "https://fsp3.docker.dev-franceconnect.fr/data-callback",
      "https://fsp3.docker.dev-franceconnect.fr/tracks-callback",
    ],
    post_logout_redirect_uris: [
      "https://fsp3.docker.dev-franceconnect.fr/logout-callback",
    ],
    key: "8ae981e67b301291d1f7d3b3b246967cfcc478d25f0aaa6b357386e02cb4476a",
    client_secret:
      "cjOdm1/StyiLtVPEOL0iynWw7lioAtv5/ShUCjNZZ5MPH3hrEosTgTC6VuZfCOu/R6Yw3NjmI2aD4Bi4p6A8JXKNC/hFrV37BstiuzGbjEDvFlLzhKNpOZCz4Kw=",
    credentialsFlow: false,
    email: "fsp3@franceconnect.loc",
    logo: "logo_Mairie de Paris_1280px-Mairie_De_Paris.svg.png",
    IPServerAddressesAndRanges: ["2.2.2.2"],
    active: true,
    type: "private",
    __v: 4,
    updatedAt: "2019-04-24 17:09:17",
    updatedBy: "admin",
    whitelistByServiceProviderActivated: true,
    whitelistByIdentityProvider: {
      "fip1-no-discovery": true,
      "fip1-low": true,
      "fip3-low": true,
    },
    scopes: [
      "openid",
      "given_name",
      "family_name",
      "preferred_username",
      "birthdate",
      "gender",
      "birthplace",
      "birthcountry",
      "dgfip_rfr",
      "dgfip_nbpart",
      "dgfip_sitfam",
      "dgfip_pac",
      "dgfip_aft",
      "cnam_paiements_ij",
      "mi_siv_carte_grise",
      "mesri_identifiant",
      "cnous_statut_boursier",
      "api_fc-liste-paiementsv1",
      "connexion_tracks",
    ],
    identityConsent: true,
    trustedIdentity: false,
    eidas: 1,
    platform: "CORE_LEGACY",
    rep_scope: [],
  },

  deprecatedTraces: {
    name: "DeprecatedTraces",
    site: "https://site.com",
    redirect_uris: [
      "https://fcp.docker.dev-franceconnect.fr/traces/login-callback",
    ],
    post_logout_redirect_uris: [
      "https://fcp.docker.dev-franceconnect.fr/traces/logout-callback",
    ],
    key: "73475cb40a568e8da8a045ced110137e159f890ac4da883b6b17dc651b3a8049",
    client_secret:
      "gUIMFjNo6pOKBBhPKPBRE0lTPIUo9mxcedLFtj90sTJVkOHjOJ42UB3c9Xbc7WI3N6jmJVFCMIU49IqE+6Z48rqP1ekczyZ3viEkfZDMZpaOc66MNQvyERC/lSU=",
    credentialsFlow: false,
    email: "users@franceconnect.loc",
    IPServerAddressesAndRanges: ["1.1.1.1"],
    active: true,
    type: "public",
    __v: 4,
    updatedAt: "2019-04-24 17:09:17",
    updatedBy: "admin",
    scopes: [
      "openid",
      "given_name",
      "family_name",
      "birthdate",
      "gender",
      "birthplace",
      "birthcountry",
      "email",
      "preferred_username",
      "address",
      "phone",
    ],
    identityConsent: false,
    trustedIdentity: false,
    eidas: 1,
    platform: "CORE_LEGACY",
    rep_scope: [],
  },

  "FS désactivé": {
    name: "FS désactivé",
    site: "https://site.com",
    redirect_uris: [
      "https://fcp.docker.dev-franceconnect.fr/traces/login-callback",
    ],
    post_logout_redirect_uris: [
      "https://fcp.docker.dev-franceconnect.fr/traces/logout-callback",
    ],
    key: "fs-desactive",
    client_secret:
      "gUIMFjNo6pOKBBhPKPBRE0lTPIUo9mxcedLFtj90sTJVkOHjOJ42UB3c9Xbc7WI3N6jmJVFCMIU49IqE+6Z48rqP1ekczyZ3viEkfZDMZpaOc66MNQvyERC/lSU=",
    credentialsFlow: false,
    email: "users@franceconnect.loc",
    IPServerAddressesAndRanges: ["1.1.1.1"],
    active: false,
    type: "public",
    __v: 4,
    updatedAt: "2019-04-24 17:09:17",
    updatedBy: "admin",
    scopes: [
      "openid",
      "given_name",
      "family_name",
      "birthdate",
      "gender",
      "birthplace",
      "birthcountry",
      "email",
      "preferred_username",
      "address",
      "phone",
    ],
    identityConsent: false,
    trustedIdentity: false,
    eidas: 1,
    platform: "CORE_LEGACY",
    rep_scope: [],
  },

  fsStats: {
    name: "FsStats",
    site: "https://site.com",
    redirect_uris: [
      "https://fsp2.docker.dev-franceconnect.fr/login-callback",
      "https://fsp2.docker.dev-franceconnect.fr/data-callback",
    ],
    post_logout_redirect_uris: [
      "https://fsp2.docker.dev-franceconnect.fr/logout-callback",
    ],
    key: "28e9ed103d6b075d371303a8bc5a66446f0cd4c0ce7ec237773276c247d28a68",
    client_secret:
      "bbg3e0zidcMLRFF7MPOUIgyOYQo2fkVR7xYLtLAEUiWGQBcXhg8X0/+K0ZXGipk/Cr4oZTYqL5MRN4y5v16MUFjFnvGffCzrn3M3w2voQhDzq8Ggj/gorS1hYhY=",
    credentialsFlow: false,
    email: "stats@stats.fr",
    logo: "logo_Mairie de Paris_1280px-Mairie_De_Paris.svg.png",
    IPServerAddressesAndRanges: ["2.2.2.2"],
    active: true,
    type: "private",
    __v: 4,
    updatedAt: "2019-04-24 17:09:17",
    updatedBy: "admin",
    blacklistByIdentityProviderActivated: true,
    blacklistByIdentityProvider: {
      fip1_blacklisted_by_fsp2: true,
    },
    scopes: [
      "openid",
      "given_name",
      "family_name",
      "birthdate",
      "gender",
      "birthplace",
      "birthcountry",
      "dgfip_rfr",
      "dgfip_nbpart",
      "dgfip_sitfam",
      "dgfip_pac",
      "dgfip_aft",
      "cnam_paiements_ij",
    ],
    identityConsent: false,
    trustedIdentity: false,
    eidas: 1,
    platform: "CORE_LEGACY",
    production_key:
      "28e9ed103d6b075d371303a8bc5a66446f0cd4c0ce7ec237773276c247d28a68",
    whitelistByServiceProviderActivated: false,
    rep_scope: [],
  },

  "user dashboard": {
    name: "User Dashboard",
    site: "https://site.com",
    redirect_uris: ["https://ud.docker.dev-franceconnect.fr/api/oidc-callback"],
    post_logout_redirect_uris: [
      "https://ud.docker.dev-franceconnect.fr/api/logout-callback",
    ],
    key: "myclientidforud-back-with-so-many-characters",
    client_secret:
      "g73pC+HYNhr2VAleGDjXo/lXHlyltxq1PavSDdoCzFC72Shd86S1e+0ch6riozdKRrIw8ax3b1ChPISIGrs9GTinFbEUXgH86/z0fppT2T+p/A7aw0msBq7Rf+8=",
    credentialsFlow: false,
    email: "users@franceconnect.loc",
    IPServerAddressesAndRanges: ["1.1.1.1"],
    active: true,
    type: "public",
    __v: 4,
    updatedAt: "2019-04-24 17:09:17",
    updatedBy: "admin",
    scopes: [
      "openid",
      "given_name",
      "family_name",
      "birthdate",
      "gender",
      "birthplace",
      "birthcountry",
      "email",
      "idp_id",
    ],
    identityConsent: false,
    id_token_signed_response_alg: "ES256",
    id_token_encrypted_response_alg: "RSA-OAEP",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "RSA-OAEP",
    userinfo_encrypted_response_enc: "A256GCM",
    jwks_uri: "https://ud.docker.dev-franceconnect.fr/.well-known/keys",
    trustedIdentity: false,
    eidas: 1,
    platform: "CORE_LEGACY",
    rep_scope: [],
  },

  MarieDeHem: {
    site: "https://site.com",
    redirect_uris: [
      "https://fsp1.docker.dev-franceconnect.fr/login-callback",
      "https://fsp1.docker.dev-franceconnect.fr/data-callback",
    ],
    post_logout_redirect_uris: [
      "https://fsp1.docker.dev-franceconnect.fr/logout-callback",
    ],
    updatedAt: "2019-05-22T14:36:12.516Z",
    key: "28e9ed103d6b075d371303a8bc5a66446f0cd4c0ce7ec237773276c247d28a95",
    client_secret:
      "4eQRa1ab1h8jIKVs53cW8FBUGIa5KQLlXQpdP/lGe3EJifIwUMHR0w6HKxu3ccGzR0y6+aS2wLAifrmhsT76TtVCvnNQAF5rONzLejQ7Hqy1LBF8TAUpx+8yFak=",
    signup_id: "1234567890",
    name: "Marie de HEM",
    email: "test@test.fr",
    contacts: [],
    IPServerAddressesAndRanges: ["1.1.1.1"],
    active: true,
    type: "public",
    secretCreatedAt: "2019-05-22T14:36:12.494Z",
    createdAt: "2019-05-22T14:36:12.493Z",
    credentialsFlow: false,
    scopes: [
      "openid",
      "given_name",
      "family_name",
      "birthdate",
      "gender",
      "birthplace",
      "birthcountry",
      "email",
      "dgfip_rfr",
      "dgfip_nbpart",
      "dgfip_sitfam",
      "dgfip_pac",
      "dgfip_aft",
    ],
    identityConsent: false,
    trustedIdentity: false,
    eidas: 1,
    platform: "CORE_LEGACY",
    __v: 0,
    rep_scope: [],
  },

  // new service pour tester les scopes
  Test_update_old_service_provider: {
    site: "https://site.com",
    redirect_uris: [
      "https://fsp1.docker.dev-franceconnect.fr/login-callback",
      "https://fsp1.docker.dev-franceconnect.fr/data-callback",
    ],
    post_logout_redirect_uris: [
      "https://fsp1.docker.dev-franceconnect.fr/logout-callback",
    ],
    updatedAt: "2019-05-22T14:36:12.516Z",
    key: "64e9ed103d6b075d371303a8bc5a66446f0cd4c0ce7ec237773276c288d28a67",
    client_secret:
      "EKMIJqIjjo0L7TmRJcdJj4QcmxMw5dLYkw20c949ezSI37tM51A2yzopBAJL+EFo5k717uIv/Ayb+hgsGu2P5Bntaa1ch+Z8QwaN5QgagJQfjMpUqqY5OUhXRHE=",
    signup_id: "14567890123",
    name: "Test_update_old_service_provider",
    email: "test@test.fr",
    contacts: [],
    IPServerAddressesAndRanges: ["1.1.1.1"],
    active: true,
    type: "public",
    secretCreatedAt: "2019-05-22T14:36:12.494Z",
    createdAt: "2019-05-22T14:36:12.493Z",
    credentialsFlow: false,
    identityConsent: false,
    trustedIdentity: false,
    eidas: 1,
    platform: "CORE_LEGACY",
    __v: 0,
    rep_scope: [],
  },
};

/* ------------------------------------------------------------------------------- */
Object.values(spLegacy).forEach((fs) => {
  print(`${fs.name} > Initializing provider: ${fs.name}`);
  db.client.update({ name: fs.name }, fs, { upsert: true });
});
