// == FS
const fsp = {
  "FSP1-LOW": {
    name: "fsp1-low",
    title: "FSP1 - LOW",
    eidas: 2,
    site: ["https://fsp1-low.docker.dev-franceconnect.fr/login"],
    redirect_uris: [
      "https://fsp1-low.docker.dev-franceconnect.fr/oidc-callback",
      "https://franceconnect.gouv.fr/",
    ],
    post_logout_redirect_uris: [
      "https://fsp1-low.docker.dev-franceconnect.fr/client/logout-callback",
      "https://franceconnect.gouv.fr/",
    ],
    sector_identifier_uri:
      "https://fsp1-low.docker.dev-franceconnect.fr/client/.well-known/sector-identifier",
    client_secret:
      "+sqGL4XE6aqzIMOp/DKC1jWB8I+8qE1jW6iz2tUv8lt+ZZzxjyoCBQeuAcJTFZxfLywkn6cAICK5JPLxYM0+8pk/q7CGHUfr/gzr3ZYRroWWE+egEEDxqRYDYe0=",
    key: "6925fb8143c76eded44d32b40c0cb1006065f7f003de52712b78985704f39950",
    entityId:
      "a0cd64372db6ecf39c317c0c74ce90f02d8ad7d510ce054883b759d666a996bc",
    credentialsFlow: false,
    email: "fsp1@franceconnect.loc",
    IPServerAddressesAndRanges: ["1.1.1.1"],
    active: true,
    type: "public",
    __v: 4,
    createdAt: new Date("2019-04-24 17:09:17"),
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    scopes: [
      "openid",
      "given_name",
      "family_name",
      "birthdate",
      "gender",
      "birthplace",
      "birthcountry",
      "email",
      "preferred_username",
      "profile",
      "birth",
      "identite_pivot",
      "idp_birthdate",
      "dgfip_rfr",
      "dgfip_aft",
      "dgfip_nbpac",
      "dgfip_nbpart",
      "dgfip_sitfam",
      "dgfip_pac",
      "droits_assurance_maladie",
      "cnam_caisse",
      "cnam_paiements_ij",
      "idp_id",
    ],
    claims: ["amr"],
    id_token_signed_response_alg: "ES256",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    idpFilterExclude: true,
    idpFilterList: ["77fe5e8c-364c-440e-909f-5ef4f494e170"],
    identityConsent: false,
    platform: "CORE_FCP",
    rep_scope: [],
    signup_id: "9992001",
  },
  // FSP2-LOW - amr not authorized
  "FSP2-LOW": {
    name: "fsp2-low",
    title: "FSP2 - LOW",
    eidas: 2,
    site: ["https://fsp2-low.docker.dev-franceconnect.fr/login"],
    redirect_uris: [
      "https://fsp2-low.docker.dev-franceconnect.fr/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://fsp2-low.docker.dev-franceconnect.fr/client/logout-callback",
    ],
    client_secret:
      "+sqGL4XE6aqzIMOp/DKC1jWB8I+8qE1jW6iz2tUv8lt+ZZzxjyoCBQeuAcJTFZxfLywkn6cAICK5JPLxYM0+8pk/q7CGHUfr/gzr3ZYRroWWE+egEEDxqRYDYe0=",
    key: "7a79e45107f9ccc6a3a5971d501220dc4fd9e87bb5e3fc62ce4104c756e22775",
    entityId:
      "a0cd64372db6ecf39c317c0c74ce90f02d8ad7d510ce054883b759d666a996bc",
    credentialsFlow: false,
    email: "fsp2@franceconnect.loc",
    IPServerAddressesAndRanges: ["1.1.1.1"],
    active: true,
    type: "public",
    __v: 4,
    createdAt: new Date("2019-04-24 17:09:17"),
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    scopes: [
      "openid",
      "given_name",
      "family_name",
      "birthdate",
      "gender",
      "birthplace",
      "birthcountry",
      "email",
      "preferred_username",
      "profile",
      "birth",
      "identite_pivot",
      "idp_birthdate",
      "dgfip_rfr",
      "dgfip_aft",
      "dgfip_nbpac",
      "dgfip_nbpart",
      "dgfip_sitfam",
      "dgfip_pac",
      "dgfip_aft",
      "droits_assurance_maladie",
      "cnam_caisse",
      "cnam_paiements_ij",
    ],
    claims: [],
    id_token_signed_response_alg: "HS256",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "HS256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    idpFilterExclude: false,
    idpFilterList: [
      "8dfc4080-c90d-4234-969b-f6c961de3e90",
      "b5e9539a-599a-4ed2-9b4f-8f4bfc5fbb64",
      "0adf04be-536e-4986-b639-73ea8d38493e",
    ],
    identityConsent: false,
    platform: "CORE_FCP",
    rep_scope: [],
    signup_id: "9992002",
  },
  // FSP3-LOW - private sp
  "FSP3-LOW": {
    name: "fsp3-low",
    title: "FSP3 - LOW",
    eidas: 1,
    site: ["https://fsp3-low.docker.dev-franceconnect.fr/login"],
    redirect_uris: [
      "https://fsp3-low.docker.dev-franceconnect.fr/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://fsp3-low.docker.dev-franceconnect.fr/client/logout-callback",
    ],
    client_secret:
      "+sqGL4XE6aqzIMOp/DKC1jWB8I+8qE1jW6iz2tUv8lt+ZZzxjyoCBQeuAcJTFZxfLywkn6cAICK5JPLxYM0+8pk/q7CGHUfr/gzr3ZYRroWWE+egEEDxqRYDYe0=",
    key: "5a6e58c6e0cf3cb21de192c567335a8ec121a3f96d0fd48cf58c1f1c48235b63",
    entityId:
      "abcd64372db6ecf39c317c0c74ce90f02d8ad7d510ce054883b759d666a996bc",
    credentialsFlow: false,
    email: "fsp3@franceconnect.loc",
    IPServerAddressesAndRanges: ["1.1.1.1"],
    active: true,
    type: "private",
    __v: 4,
    createdAt: new Date("2019-04-24 17:09:17"),
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    scopes: [
      "openid",
      "given_name",
      "family_name",
      "birthdate",
      "gender",
      "birthplace",
      "birthcountry",
      "email",
      "preferred_username",
      "profile",
      "birth",
      "identite_pivot",
      "idp_birthdate",
      "dgfip_rfr",
      "dgfip_aft",
      "dgfip_nbpac",
      "dgfip_nbpart",
      "dgfip_sitfam",
      "dgfip_pac",
      "dgfip_aft",
      "droits_assurance_maladie",
      "cnam_caisse",
      "cnam_paiements_ij",
    ],
    claims: ["amr"],
    id_token_signed_response_alg: "HS256",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "HS256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    idpFilterExclude: true,
    idpFilterList: ["0adf04be-536e-4986-b639-73ea8d38493e"],
    identityConsent: true,
    platform: "CORE_FCP",
    rep_scope: [
      "Papier-Citoyenneté-Elections",
      "Famille-Scolarité",
      "Social-Santé",
      "Travail-Formation",
    ],
    signup_id: "9992003",
  },
  // FSP4-LOW - whitelist fip8
  "FSP4-LOW": {
    name: "fsp4-low",
    title: "FSP4 - LOW",
    eidas: 1,
    site: ["https://fsp4-low.docker.dev-franceconnect.fr/login"],
    redirect_uris: [
      "https://fsp4-low.docker.dev-franceconnect.fr/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://fsp4-low.docker.dev-franceconnect.fr/client/logout-callback",
    ],
    client_secret:
      "+sqGL4XE6aqzIMOp/DKC1jWB8I+8qE1jW6iz2tUv8lt+ZZzxjyoCBQeuAcJTFZxfLywkn6cAICK5JPLxYM0+8pk/q7CGHUfr/gzr3ZYRroWWE+egEEDxqRYDYe0=",
    key: "6925fb7843c76eded44d32b40c0cb1gyu065f7f003de52712b78985704f39950",
    entityId:
      "a0cd64372db6ecf39c317c0c74ce90f02d8ad7d510ce054883b759d666a996bc",
    credentialsFlow: false,
    email: "fsp4@franceconnect.loc",
    IPServerAddressesAndRanges: ["1.1.1.1"],
    active: true,
    type: "public",
    __v: 4,
    createdAt: new Date("2019-04-24 17:09:17"),
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    scopes: [
      "openid",
      "given_name",
      "family_name",
      "birthdate",
      "gender",
      "birthplace",
      "birthcountry",
      "email",
      "preferred_username",
      "profile",
      "birth",
      "identite_pivot",
      "idp_birthdate",
      "dgfip_rfr",
      "dgfip_aft",
      "dgfip_nbpac",
      "dgfip_nbpart",
      "dgfip_sitfam",
      "dgfip_pac",
      "dgfip_aft",
      "droits_assurance_maladie",
      "cnam_caisse",
      "cnam_paiements_ij",
    ],
    claims: ["amr"],
    id_token_signed_response_alg: "HS256",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "HS256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    idpFilterExclude: false,
    idpFilterList: ["77fe5e8c-364c-440e-909f-5ef4f494e170"],
    identityConsent: false,
    platform: "CORE_FCP",
    rep_scope: [],
    signup_id: "9992004",
  },

  // FSP5-LOW: identical to FSP4-LOW but with invalid sector_identifier_uri
  "FSP5-LOW": {
    name: "fsp5-low",
    title: "FSP5 - LOW",
    eidas: 1,
    site: ["https://fsp4-low.docker.dev-franceconnect.fr/login"],
    redirect_uris: [
      "https://fsp4-low.docker.dev-franceconnect.fr/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://fsp4-low.docker.dev-franceconnect.fr/client/logout-callback",
    ],
    sector_identifier_uri:
      "https://fsp4-low.docker.dev-franceconnect.fr/not-a-valid-uri",
    client_secret:
      "+sqGL4XE6aqzIMOp/DKC1jWB8I+8qE1jW6iz2tUv8lt+ZZzxjyoCBQeuAcJTFZxfLywkn6cAICK5JPLxYM0+8pk/q7CGHUfr/gzr3ZYRroWWE+egEEDxqRYDYe0=",
    key: "5925fb7843c76eded44d32b40c0cb1gyu065f7f003de52712b78985704f39950",
    entityId:
      "z0cd64372db6ecf39c317c0c74ce90f02d8ad7d510ce054883b759d666a996bc",
    credentialsFlow: false,
    email: "fsp4@franceconnect.loc",
    IPServerAddressesAndRanges: ["1.1.1.1"],
    active: true,
    type: "public",
    __v: 4,
    createdAt: new Date("2019-04-24 17:09:17"),
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    scopes: ["openid"],
    claims: ["amr"],
    id_token_signed_response_alg: "ES256",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    idpFilterExclude: false,
    idpFilterList: ["77fe5e8c-364c-440e-909f-5ef4f494e170"],
    identityConsent: false,
    platform: "CORE_FCP",
    rep_scope: [],
    signup_id: "9992005",
  },
  "user dashboard": {
    name: "User Dashboard",
    title: "Tableau de bord",
    site: ["https://ud.docker.dev-franceconnect.fr/"],
    redirect_uris: ["https://ud.docker.dev-franceconnect.fr/api/oidc-callback"],
    post_logout_redirect_uris: [
      "https://ud.docker.dev-franceconnect.fr/api/logout-callback",
    ],
    key: "myclientidforud-back-with-so-many-characters",
    entityId: "myclientidforud-back-with-so-many-characters",
    client_secret:
      "g73pC+HYNhr2VAleGDjXo/lXHlyltxq1PavSDdoCzFC72Shd86S1e+0ch6riozdKRrIw8ax3b1ChPISIGrs9GTinFbEUXgH86/z0fppT2T+p/A7aw0msBq7Rf+8=",
    credentialsFlow: false,
    email: "users@franceconnect.loc",
    IPServerAddressesAndRanges: ["1.1.1.1"],
    active: true,
    type: "public",
    __v: 4,
    createdAt: new Date("2019-04-24 17:09:17"),
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    scopes: [
      "openid",
      "given_name",
      "family_name",
      "birthdate",
      "gender",
      "birthplace",
      "birthcountry",
      "email",
      "idp_id",
    ],
    claims: ["amr"],
    identityConsent: false,
    idpFilterExclude: true,
    idpFilterList: [],
    id_token_signed_response_alg: "ES256",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    jwks_uri:
      "https://ud.docker.dev-franceconnect.fr/api/client/.well-known/keys",
    eidas: 1,
    platform: "CORE_FCP",
    rep_scope: [],
    signup_id: "9992100",
  },
};

/* ------------------------------------------------------------------------------- */
Object.values(fsp).forEach((fs) => {
  print(`${fs.name} > Initializing provider: ${fs.name}`);
  db.client.updateOne({ name: fs.name }, { $set: fs }, { upsert: true });
});
