services:
  wallet:
    image: ${DOCKER_HUB_PROXY}alpine
    depends_on:
      - "min-fcp-low"
      - "wallet-bridge-devtools"
      - "mock-wallet"

  bdd-wallet:
    image: ${DOCKER_HUB_PROXY}alpine
    depends_on:
      - "min-fcp-high"
      - "min-fcp-low"
      - "wallet-bridge"
      - "mock-wallet"
