services:
  ####################
  # Wallet Bridge - FC+ (high)
  ####################
  wallet-bridge-high:
    hostname: wallet-bridge-high
    image: ${FC_DOCKER_REGISTRY}/nodejs:${NODE_VERSION}-dev
    user: ${CURRENT_UID}
    working_dir: /var/www/app
    depends_on:
      node-modules-back:
        condition: service_completed_successfully
      redis-pwd:
        condition: service_healthy
      squid:
        condition: service_started
    volumes:
      - "${VOLUMES_DIR}/src/fc/back:/var/www/app"
      - "${VOLUMES_DIR}/app:/opt/scripts"
      - "${VOLUMES_DIR}/log:/var/log/app"
      - "${VOLUMES_DIR}/.home:/home"
      - "${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro"
    env_file:
      - "${COMPOSE_DIR}/shared/.env/base-app.env"
      - "${COMPOSE_DIR}/wallet-bridge/.env/wallet-bridge.env"
      - "${COMPOSE_DIR}/wallet-bridge/.env/wallet-bridge-high.env"
    tty: true
    networks:
      - public
      - data
    init: true
    command: "pm2 logs"

  ####################
  # Wallet Bridge - FC (low)
  ####################
  wallet-bridge-low:
    hostname: wallet-bridge-low
    image: ${FC_DOCKER_REGISTRY}/nodejs:${NODE_VERSION}-dev
    user: ${CURRENT_UID}
    working_dir: /var/www/app
    depends_on:
      node-modules-back:
        condition: service_completed_successfully
      redis-pwd:
        condition: service_healthy
      squid:
        condition: service_started
    volumes:
      - "${VOLUMES_DIR}/src/fc/back:/var/www/app"
      - "${VOLUMES_DIR}/app:/opt/scripts"
      - "${VOLUMES_DIR}/log:/var/log/app"
      - "${VOLUMES_DIR}/.home:/home"
      - "${VOLUMES_DIR}/ssl:/etc/ssl/docker_host:ro"
    env_file:
      - "${COMPOSE_DIR}/shared/.env/base-app.env"
      - "${COMPOSE_DIR}/wallet-bridge/.env/wallet-bridge.env"
      - "${COMPOSE_DIR}/wallet-bridge/.env/wallet-bridge-low.env"
    tty: true
    networks:
      - public
      - data
    init: true
    command: "pm2 logs"
