// == FI
const fip = {
  // -- FIP - FIP1-HIGH - Activated
  "FIP1-HIGH": {
    uid: "fip1-high",
    name: "fip1-high",
    active: true,
    display: true,
    title: "IDP1 - Identity Provider - eIDAS élevé - nodiscov - crypt",
    image: "fi-mock-eleve.svg",
    imageFocus: "fi-mock-eleve.svg",
    alt: "IDP1 - Identity Provider - eIDAS élevé - nodiscov - crypt",
    eidas: 3,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip1-high",
    url: "https://fip1-high.docker.dev-franceconnect.fr",
    tokenURL: "https://fip1-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip1-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL:
      "https://fip1-high.docker.dev-franceconnect.fr/user/session/end",
    statusURL: "https://fip1-high.docker.dev-franceconnect.fr/",
    jwksURL: "https://fip1-high.docker.dev-franceconnect.fr/jwks",
    authzURL: "https://fip1-high.docker.dev-franceconnect.fr/authorize",
    discovery: false,
    response_types: ["code"],
    clientID: "09a1a257648c1742c74d6a3d84b31943",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "RSA-OAEP",
    userinfo_encrypted_response_enc: "A256GCM",
    redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
    ],
  },

  // -- FIP - FIP2-HIGH - Activated
  "FIP2-HIGH": {
    uid: "fip2-high",
    name: "fip2-high",
    active: true,
    display: true,
    title: "IDP2 - Identity Provider - eIDAS élevé - nodiscov - nocrypt",
    image: "fi-mock-eleve.svg",
    imageFocus: "fi-mock-eleve.svg",
    alt: "IDP2 - Identity Provider - eIDAS élevé - nodiscov - nocrypt",
    eidas: 3,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip2-high",
    url: "https://fip2-high.docker.dev-franceconnect.fr",
    tokenURL: "https://fip2-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip2-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL:
      "https://fip2-high.docker.dev-franceconnect.fr/user/session/end",
    statusURL: "https://fip2-high.docker.dev-franceconnect.fr/",
    jwksURL: "https://fip2-high.docker.dev-franceconnect.fr/jwks",
    authzURL: "https://fip2-high.docker.dev-franceconnect.fr/authorize",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip2-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "RS256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "RS256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback/fip2-high",
    ],
    post_logout_redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
    ],
  },
  // -- FIP - FIP3-HIGH - Deactivated but visible
  "FIP3-HIGH": {
    uid: "fip3-desactive-visible",
    name: "fip3-desactive-visible",
    active: false,
    display: true,
    title: "FIP3 - FI désactivé mais visible",
    image: "fi-mock-eleve.svg",
    imageFocus: "fi-mock-eleve.svg",
    alt: "FIP3 - FI désactivé mais visible",
    eidas: 3,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip3-high",
    url: "https://fip3-high.docker.dev-franceconnect.fr",
    tokenURL: "https://fip3-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip3-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL:
      "https://fip3-high.docker.dev-franceconnect.fr/user/session/end",
    statusURL: "https://fip3-high.docker.dev-franceconnect.fr/",
    jwksURL: "https://fip3-high.docker.dev-franceconnect.fr/jwks",
    authzURL: "https://fip3-high.docker.dev-franceconnect.fr/authorize",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip-desactive-visible",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "RSA-OAEP",
    userinfo_encrypted_response_enc: "A256GCM",
    redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
    ],
  },
  // -- FIP - FIP4-HIGH - Deactivated and invisible
  // use fip1 urls to avoid the generation of a container
  "FIP4-HIGH": {
    uid: "fip4-desactive-invisible",
    name: "fip4-desactive-invisible",
    active: false,
    display: false,
    title: "FIP4 - FI désactivé et invisible",
    image: "fi-mock-eleve.svg",
    imageFocus: "fi-mock-eleve.svg",
    alt: "FIP4 - FI désactivé et invisible",
    eidas: 3,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip4-high",
    url: "https://fip1-high.docker.dev-franceconnect.fr",
    tokenURL: "https://fip1-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip1-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL:
      "https://fip1-high.docker.dev-franceconnect.fr/user/session/end",
    statusURL: "https://fip1-high.docker.dev-franceconnect.fr/",
    jwksURL: "https://fip1-high.docker.dev-franceconnect.fr/jwks",
    authzURL: "https://fip1-high.docker.dev-franceconnect.fr/authorize",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip4-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "RSA-OAEP",
    userinfo_encrypted_response_enc: "A256GCM",
    redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
    ],
  },
  // -- FIP - FIP5-HIGH - Activated and invisible
  // use fip1 urls to avoid the generation of a container
  "FIP5-HIGH": {
    uid: "fip5-active-invisible",
    name: "fip5-active-invisible",
    active: true,
    display: false,
    title: "FIP5 - FI activé et invisible",
    image: "fi-mock-eleve.svg",
    imageFocus: "fi-mock-eleve.svg",
    alt: "FIP5 - FI activé et invisible",
    eidas: 3,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip5-high",
    url: "https://fip1-high.docker.dev-franceconnect.fr",
    tokenURL: "https://fip1-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip1-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL:
      "https://fip1-high.docker.dev-franceconnect.fr/user/session/end",
    statusURL: "https://fip1-high.docker.dev-franceconnect.fr/",
    jwksURL: "https://fip1-high.docker.dev-franceconnect.fr/jwks",
    authzURL: "https://fip1-high.docker.dev-franceconnect.fr/authorize",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip5-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "RSA-OAEP",
    userinfo_encrypted_response_enc: "A256GCM",
    redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
    ],
  },
  // -- FIP - FIP6-HIGH
  "FIP6-HIGH": {
    uid: "fip6-high",
    name: "fip6-high",
    active: true,
    display: true,
    title:
      "IDP6 - Identity Provider - eIDAS élevé - whitelisted - nodiscov - crypt",
    image: "fi-mock-eleve.svg",
    imageFocus: "fi-mock-eleve.svg",
    alt: "IDP6 - Identity Provider - eIDAS élevé - whitelisted - nodiscov - crypt",
    eidas: 3,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip6-high",
    url: "https://fip6-high.docker.dev-franceconnect.fr",
    tokenURL: "https://fip6-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip6-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL:
      "https://fip6-high.docker.dev-franceconnect.fr/user/session/end",
    statusURL: "https://fip6-high.docker.dev-franceconnect.fr/",
    jwksURL: "https://fip6-high.docker.dev-franceconnect.fr/jwks",
    authzURL: "https://fip6-high.docker.dev-franceconnect.fr/authorize",
    discovery: false,
    response_types: ["code"],
    clientID: "69a1a257648c1742c74d6a3d84b31943",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "RSA-OAEP",
    userinfo_encrypted_response_enc: "A256GCM",
    redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
    ],
  },
  // -- FIP - FIP7-HIGH - no discovery attribute
  // use fip1 urls to avoid the generation of a container
  "FIP7-HIGH": {
    uid: "fip7-high",
    name: "fip7-high",
    active: true,
    display: true,
    title:
      "IDP7 - Identity Provider - eIDAS élevé - blacklisted - discov - nocrypt",
    image: "fi-mock-eleve.svg",
    imageFocus: "fi-mock-eleve.svg",
    alt: "IDP7 - Identity Provider - eIDAS élevé - blacklisted - discov - nocrypt",
    eidas: 3,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip7-high",
    url: "https://fip1-high.docker.dev-franceconnect.fr",
    statusURL: "https://fip1-high.docker.dev-franceconnect.fr/",
    // discovery: true,
    discoveryUrl:
      "https://fip1-high.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    response_types: ["code"],
    clientID: "79a1a257648c1742c74d6a3d84b31943",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
    ],
  },
  // -- FIP - FIP8-HIGH - blacklisted
  // use fip1 urls to avoid the generation of a container
  // Blacklisted by FSP2
  // Absent of FSP5 whitelist
  "FIP8-HIGH": {
    uid: "fip8-high",
    name: "fip8-high",
    active: true,
    display: true,
    title:
      "IDP8 - Identity Provider - eIDAS élevé - whitelisted - discov - crypt",
    image: "fi-mock-eleve.svg",
    imageFocus: "fi-mock-eleve.svg",
    alt: "IDP8 - Identity Provider - eIDAS élevé - whitelisted - discov - crypt",
    eidas: 3,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip8-high",
    url: "https://fip1-high.docker.dev-franceconnect.fr",
    statusURL: "https://fip1-high.docker.dev-franceconnect.fr/",
    discovery: true,
    discoveryUrl:
      "https://fip1-high.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    response_types: ["code"],
    clientID: "09a1a257648c1742c74d6a3d84b31943",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "RSA-OAEP",
    userinfo_encrypted_response_enc: "A256GCM",
    redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
    ],
  },
  // -- FIP - FIP9-HIGH - no discovery url
  // use fip1 urls to avoid the generation of a container
  "FIP9-HIGH": {
    uid: "fip9-high",
    name: "fip9-high",
    active: true,
    display: true,
    title:
      "IDP9 - Identity Provider - eIDAS élevé - whitelisted - discov - crypt",
    image: "fi-mock-eleve.svg",
    imageFocus: "fi-mock-eleve.svg",
    alt: "IDP9 - Identity Provider - eIDAS élevé - whitelisted - discov - crypt",
    eidas: 3,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip9-high",
    url: "https://fip1-high.docker.dev-franceconnect.fr",
    statusURL: "https://fip1-high.docker.dev-franceconnect.fr/",
    discovery: true,
    // discoveryUrl:
    //  "https://fip1-high.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    response_types: ["code"],
    clientID: "09a1a257648c1742c74d6a3d84b31943",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "RSA-OAEP",
    userinfo_encrypted_response_enc: "A256GCM",
    redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
    ],
  },
  // -- FIP - FIP10-HIGH - invalid parameter
  // use fip1 urls to avoid the generation of a container
  "FIP10-HIGH": {
    uid: "fip10-high",
    name: "fip10-high",
    active: true,
    display: true,
    title:
      "IDP10 - Identity Provider - eIDAS élevé - whitelisted - discov - crypt",
    image: "fi-mock-eleve.svg",
    imageFocus: "fi-mock-eleve.svg",
    alt: "IDP10 - Identity Provider - eIDAS élevé - whitelisted - discov - crypt",
    eidas: 3,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip10-high",
    url: "https://fip1-high.docker.dev-franceconnect.fr",
    statusURL: "https://fip1-high.docker.dev-franceconnect.fr/",
    discovery: true,
    discoveryUrl:
      "https://fip1-high.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    // Invalid parameter when using discovery, for testing purpose
    authzURL: "https://fip1-high.docker.dev-franceconnect.fr/user/authorize",
    response_types: ["code"],
    clientID: "09a1a257648c1742c74d6a3d84b31943",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "RS256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "RS256",
    userinfo_encrypted_response_alg: "RSA-OAEP",
    userinfo_encrypted_response_enc: "A256GCM",
    redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
    ],
  },
  // -- FIP - FIP11-HIGH
  // use fip1 urls to avoid the generation of a container
  "FIP11-HIGH": {
    uid: "fip11-high",
    name: "fip11-high",
    active: true,
    display: true,
    title:
      "IDP11 - Identity Provider - eIDAS élevé - whitelisted - nodiscov - crypt",
    image: "fi-mock-eleve.svg",
    imageFocus: "fi-mock-eleve.svg",
    alt: "IDP11 - Identity Provider - eIDAS élevé - whitelisted - nodiscov - crypt",
    eidas: 3,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip11-high",
    url: "https://fip1-high.docker.dev-franceconnect.fr",
    tokenURL: "https://fip1-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip1-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL:
      "https://fip1-high.docker.dev-franceconnect.fr/user/session/end",
    statusURL: "https://fip1-high.docker.dev-franceconnect.fr/",
    jwksURL: "https://fip1-high.docker.dev-franceconnect.fr/jwks",
    authzURL: "https://fip1-high.docker.dev-franceconnect.fr/authorize",
    discovery: false,
    response_types: ["code"],
    clientID: "09a1a257648c1742c74d6a3d84b31943",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "RS256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "RS256",
    userinfo_encrypted_response_alg: "RSA-OAEP",
    userinfo_encrypted_response_enc: "A256GCM",
    redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
    ],
  },
  // -- FIP - IDP12-HIGH - Identity Provider not respecting the DTO
  // use fip1 urls to avoid the generation of a container
  "FIP12-HIGH": {
    uid: "fip12-high",
    name: "fip12-high",
    active: true,
    display: true,
    title:
      "IDP12 - Identity Provider - eIDAS élevé - crypted (ECDH-ES + A256GCM) - signed (ES256)",
    image: "fi-mock-eleve.svg",
    imageFocus: "fi-mock-eleve.svg",
    alt: "IDP12 - Identity Provider - eIDAS élevé - crypted (ECDH-ES + A256GCM) - signed (ES256)",
    eidas: 3,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip12-high",
    url: "https://fip1-high.docker.dev-franceconnect.fr",
    tokenURL: "https://fip1-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip1-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL:
      "https://fip1-high.docker.dev-franceconnect.fr/user/session/end",
    statusURL: "https://fip1-high.docker.dev-franceconnect.fr/",
    jwksURL: "https://fip1-high.docker.dev-franceconnect.fr/jwks",
    // Remove the authorize to not pass the DTO for tests purposes
    // authzURL: "https://fip1-high.docker.dev-franceconnect.fr/authorize",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip13-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "ECDH-ES",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "ECDH-ES",
    userinfo_encrypted_response_enc: "A256GCM",
    redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
    ],
  },
  // -- FIP - FIP13V2 - Activated - eIDAS élevé - crypted (ECDH-ES + A256GCM) - signed (ES256)
  "FIP13-HIGH": {
    uid: "fip13-high",
    name: "fip13-high",
    active: true,
    display: true,
    title:
      "IDP13 - Identity Provider - eIDAS élevé - crypted (ECDH-ES + A256GCM) - signed (ES256)",
    image: "fi-mock-eleve.svg",
    imageFocus: "fi-mock-eleve.svg",
    alt: "impots",
    eidas: 3,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip13-high",
    url: "https://fip13-high.docker.dev-franceconnect.fr",
    tokenURL: "https://fip13-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip13-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL:
      "https://fip13-high.docker.dev-franceconnect.fr/user/session/end",
    statusURL: "https://fip13-high.docker.dev-franceconnect.fr/",
    jwksURL: "https://fip13-high.docker.dev-franceconnect.fr/jwks",
    authzURL: "https://fip13-high.docker.dev-franceconnect.fr/authorize",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip13-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "ECDH-ES",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "ECDH-ES",
    userinfo_encrypted_response_enc: "A256GCM",
    redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
    ],
  },

  // -- FIP - FIP14V2 - Activated - eIDAS élevé - crypted (RSA-OAEP + A256GCM) - signed (RS256)
  "FIP14-HIGH": {
    uid: "fip14-high",
    name: "fip14-high",
    active: true,
    display: true,
    title:
      "IDP14 - Identity Provider - eIDAS élevé - crypted (RSA-OAEP + A256GCM) - signed (RS256)",
    image: "fi-mock-eleve.svg",
    imageFocus: "fi-mock-eleve.svg",
    alt: "impots",
    eidas: 3,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip14-high",
    url: "https://fip14-high.docker.dev-franceconnect.fr",
    statusURL: "https://fip14-high.docker.dev-franceconnect.fr/",
    authzURL: "https://fip14-high.docker.dev-franceconnect.fr/authorize",
    tokenURL: "https://fip14-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip14-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL:
      "https://fip14-high.docker.dev-franceconnect.fr/user/session/end",
    jwksURL: "https://fip14-high.docker.dev-franceconnect.fr/jwks",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip14-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "RS256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "RS256",
    userinfo_encrypted_response_alg: "RSA-OAEP",
    userinfo_encrypted_response_enc: "A256GCM",
    redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
    ],
  },

  // -- FIP - FIP15V2 - Activated - eIDAS substantiel - crypted (RSA-OAEP + A256GCM) - signed (ES256)
  "FIP15-HIGH": {
    uid: "fip15-high",
    name: "fip15-high",
    active: true,
    display: true,
    title:
      "IDP15 - Identity Provider - eIDAS substantiel - crypted (RSA-OAEP + A256GCM) - signed (ES256)",
    image: "fi-mock-substantiel.svg",
    imageFocus: "fi-mock-substantiel.svg",
    alt: "impots",
    eidas: 2,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip15-high",
    url: "https://fip15-high.docker.dev-franceconnect.fr",
    statusURL: "https://fip15-high.docker.dev-franceconnect.fr/",
    authzURL: "https://fip15-high.docker.dev-franceconnect.fr/authorize",
    tokenURL: "https://fip15-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip15-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL:
      "https://fip15-high.docker.dev-franceconnect.fr/user/session/end",
    jwksURL: "https://fip15-high.docker.dev-franceconnect.fr/jwks",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip15-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    endSessionURL:
      "https://fip15-high.docker.dev-franceconnect.fr/user/session/end",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "RSA-OAEP",
    userinfo_encrypted_response_enc: "A256GCM",
    redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
    ],
  },

  // -- FIP - FIP16V2 - Activated - eIDAS substantiel - crypted (ECDH-ES + A256GCM) - signed (RS256)
  "FIP16-HIGH": {
    uid: "fip16-high",
    name: "fip16-high",
    active: true,
    display: true,
    title:
      "IDP16 - Identity Provider - eIDAS substantiel - crypted (ECDH-ES + A256GCM) - signed (RS256)",
    image: "fi-mock-substantiel.svg",
    imageFocus: "fi-mock-substantiel.svg",
    alt: "impots",
    eidas: 2,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip16-high",
    url: "https://fip16-high.docker.dev-franceconnect.fr",
    statusURL: "https://fip16-high.docker.dev-franceconnect.fr/",
    authzURL: "https://fip16-high.docker.dev-franceconnect.fr/authorize",
    tokenURL: "https://fip16-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip16-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL:
      "https://fip16-high.docker.dev-franceconnect.fr/user/session/end",
    jwksURL: "https://fip16-high.docker.dev-franceconnect.fr/jwks",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip16-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "RS256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "ECDH-ES",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "RS256",
    userinfo_encrypted_response_alg: "ECDH-ES",
    userinfo_encrypted_response_enc: "A256GCM",
    redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
    ],
  },

  // -- FIP - FIP17V2 - Activated - eIDAS substantiel - crypted (none) - signed (ES256)
  "FIP17-HIGH": {
    uid: "fip17-high",
    name: "fip17-high",
    active: true,
    display: true,
    title:
      "IDP17 - Identity Provider - eIDAS substantiel - crypted (none) - signed (ES256)",
    image: "fi-mock-substantiel.svg",
    imageFocus: "fi-mock-substantiel.svg",
    alt: "impots",
    eidas: 2,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip17-high",
    url: "https://fip17-high.docker.dev-franceconnect.fr",
    authzURL: "https://fip17-high.docker.dev-franceconnect.fr/authorize",
    tokenURL: "https://fip17-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip17-high.docker.dev-franceconnect.fr/userinfo",
    statusURL: "https://fip17-high.docker.dev-franceconnect.fr/",
    endSessionURL:
      "https://fip17-high.docker.dev-franceconnect.fr/user/session/end",
    jwksURL: "https://fip17-high.docker.dev-franceconnect.fr/jwks",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip17-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
    ],
  },

  // -- FIP - FIP18V2 - Activated - eIDAS faible - crypted (none) - signed (ES256)
  "FIP18-HIGH": {
    uid: "fip18-high",
    name: "fip18-high",
    active: true,
    display: true,
    title:
      "IDP18 - Identity Provider - eIDAS faible - crypted (none) - signed (ES256)",
    image: "fi-mock-faible.svg",
    imageFocus: "fi-mock-faible.svg",
    alt: "impots",
    eidas: 1,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip18-high",
    url: "https://fip18-high.docker.dev-franceconnect.fr",
    statusURL: "https://fip18-high.docker.dev-franceconnect.fr/",
    authzURL: "https://fip18-high.docker.dev-franceconnect.fr/authorize",
    tokenURL: "https://fip18-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip18-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL:
      "https://fip18-high.docker.dev-franceconnect.fr/user/session/end",
    jwksURL: "https://fip18-high.docker.dev-franceconnect.fr/jwks",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip18-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",

    redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
    ],
  },

  // -- FIP - FIP19V2 - Activated - eIDAS faible - crypted (none) - signed (RS256)
  "FIP19-HIGH": {
    uid: "fip19-high",
    name: "fip19-high",
    active: true,
    display: true,
    title:
      "IDP19 - Identity Provider - eIDAS faible - crypted (none) - signed (RS256)",
    image: "fi-mock-faible.svg",
    imageFocus: "fi-mock-faible.svg",
    alt: "impots",
    eidas: 1,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip19-high",
    url: "https://fip19-high.docker.dev-franceconnect.fr",
    statusURL: "https://fip19-high.docker.dev-franceconnect.fr/",
    authzURL: "https://fip19-high.docker.dev-franceconnect.fr/authorize",
    tokenURL: "https://fip19-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip19-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL:
      "https://fip19-high.docker.dev-franceconnect.fr/user/session/end",
    jwksURL: "https://fip19-high.docker.dev-franceconnect.fr/jwks",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip19-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "RS256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "RS256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
    ],
  },

  // -- FIP - FIP20V2 - Activated - eIDAS faible - crypted (none) - signed (HS256)
  "FIP20-HIGH": {
    uid: "fip20-high",
    name: "fip20-high",
    active: true,
    display: true,
    title:
      "IDP20 - Identity Provider - eIDAS faible - crypted (none) - signed (HS256)",
    image: "fi-mock-faible.svg",
    imageFocus: "fi-mock-faible.svg",
    alt: "impots",
    eidas: 1,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip20-high",
    url: "https://fip20-high.docker.dev-franceconnect.fr",
    statusURL: "https://fip20-high.docker.dev-franceconnect.fr/",
    authzURL: "https://fip20-high.docker.dev-franceconnect.fr/authorize",
    tokenURL: "https://fip20-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip20-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL:
      "https://fip20-high.docker.dev-franceconnect.fr/user/session/end",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip20-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "HS256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "HS256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
    ],
  },

  // -- FIPEIDAS - FIPEIDASV2 - Activated
  EIDASBRIDGE: {
    uid: "eidas-bridge",
    url: "https://eidas-bridge.docker.dev-franceconnect.fr",
    name: "eidas-bridge",
    image: "demonstration_eleve.png",
    title: "eIDAS Identity Provider",
    active: true,
    display: true,
    featureHandlers: {
      coreVerify: "core-fcp-eidas-verify",
      authenticationEmail: null,
      idpIdentityCheck: "core-fcp-eidas-identity-check",
    },
    clientID: "myclientidforeidas-bridge",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/oidc-callback/eidas-bridge",
    ],
    post_logout_redirect_uris: [
      "https://core-fcp-high.docker.dev-franceconnect.fr/api/v2/logout/redirect-from-idp",
    ],
    response_types: ["code"],
    revocation_endpoint_auth_method: "client_secret_post",
    discovery: false,
    authzURL: "https://eidas-bridge.docker.dev-franceconnect.fr/authorize",
    tokenURL: "https://eidas-bridge.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://eidas-bridge.docker.dev-franceconnect.fr/userinfo",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "RSA-OAEP",
    userinfo_encrypted_response_enc: "A256GCM",
    id_token_signed_response_alg: "ES256",
    id_token_encrypted_response_alg: "RSA-OAEP",
    id_token_encrypted_response_enc: "A256GCM",
    token_endpoint_auth_method: "client_secret_post",
    jwksURL: "https://eidas-bridge.docker.dev-franceconnect.fr/jwks",

    // metadata
    imageFocus: "demonstration_eleve_hover.png",
    alt: "impots",
    eidas: 3,
    mailto: "",
    specificText: "specific text fip1-high",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    endSessionURL:
      "https://eidas-bridge.docker.dev-franceconnect.fr/session/end",
    statusURL: "https://eidas-bridge.docker.dev-franceconnect.fr/",
  },
};

// -- FIs ----------

Object.values(fip).forEach((fi) => {
  print(`FIP > Initializing provider: ${fi.name} - Activated`);
  db.provider.update({ uid: fi.uid }, fi, { upsert: true });
});
