// == FI
const fip = {
  // -- FIP - FIP1-HIGH - Activated - Discovery true
  "FIP1-HIGH": {
    uid: "dedc7160-8811-4d0f-9dd7-c072c15f2f18",
    name: "fip1-high",
    active: true,
    display: true,
    isBeta: false,
    title: "IDP1 - Identity Provider - eIDAS élevé - discov - crypt",
    image: "fi-mock-eleve.svg",
    imageFocus: "fi-mock-eleve.svg",
    alt: "IDP1 - Identity Provider - eIDAS élevé - discov - crypt",
    trustedIdentity: false,
    eidas: 3,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip1-high",
    url: "https://fip1-high.docker.dev-franceconnect.fr",
    discovery: true,
    discoveryUrl:
      "https://fip1-high.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    response_types: ["code"],
    clientID: "09a1a257648c1742c74d6a3d84b31943",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 1,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP-256",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "RSA-OAEP-256",
    userinfo_encrypted_response_enc: "A256GCM",
    amr: ["fc", "pwd", "mail", "mfa"],
  },

  // -- FIP - FIP2-HIGH - Activated
  // Without endSessionURL
  "FIP2-HIGH": {
    uid: "f9a3f6fe-f9b3-4cec-b787-33713fdffc79",
    name: "fip2-high",
    active: true,
    display: true,
    isBeta: false,
    title: "IDP2 - Identity Provider - eIDAS élevé - nodiscov - nocrypt",
    image: "",
    imageFocus: "",
    alt: "IDP2 - Identity Provider - eIDAS élevé - nodiscov - nocrypt",
    trustedIdentity: false,
    eidas: 3,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip2-high",
    url: "https://fip2-high.docker.dev-franceconnect.fr",
    tokenURL: "https://fip2-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip2-high.docker.dev-franceconnect.fr/userinfo",
    // endSessionURL: "https://fip2-high.docker.dev-franceconnect.fr/session/end",
    statusURL: "https://fip2-high.docker.dev-franceconnect.fr/",
    jwksURL: "https://fip2-high.docker.dev-franceconnect.fr/jwks",
    authzURL: "https://fip2-high.docker.dev-franceconnect.fr/authorize",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip2-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 2,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "RS256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "RS256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    amr: ["fc", "pwd", "mail"],
  },
  // -- FIP - FIP3-HIGH - Deactivated but visible
  "FIP3-HIGH": {
    uid: "621c3c17-5f49-4ca5-b8ef-a4b1cecaf7c2",
    name: "fip3-desactive-visible",
    active: false,
    display: true,
    isBeta: false,
    title: "FIP3 - FI désactivé mais visible",
    image: "",
    imageFocus: "",
    alt: "FIP3 - FI désactivé mais visible",
    trustedIdentity: false,
    eidas: 3,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip3-high",
    url: "https://fip3-high.docker.dev-franceconnect.fr",
    tokenURL: "https://fip3-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip3-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL: "https://fip3-high.docker.dev-franceconnect.fr/session/end",
    statusURL: "https://fip3-high.docker.dev-franceconnect.fr/",
    jwksURL: "https://fip3-high.docker.dev-franceconnect.fr/jwks",
    authzURL: "https://fip3-high.docker.dev-franceconnect.fr/authorize",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip-desactive-visible",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 3,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "RSA-OAEP",
    userinfo_encrypted_response_enc: "A256GCM",
    amr: ["fc", "pwd", "mail"],
  },
  // -- FIP - FIP4-HIGH - Deactivated and invisible
  // use fip1 urls to avoid the generation of a container
  "FIP4-HIGH": {
    uid: "ce0f6c4d-d70e-411e-a8a0-2a66afa7bd90",
    name: "fip4-desactive-invisible",
    active: false,
    display: false,
    isBeta: false,
    title: "FIP4 - FI désactivé et invisible",
    image: "",
    imageFocus: "",
    alt: "FIP4 - FI désactivé et invisible",
    trustedIdentity: false,
    eidas: 3,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip4-high",
    url: "https://fip1-high.docker.dev-franceconnect.fr",
    tokenURL: "https://fip1-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip1-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL: "https://fip1-high.docker.dev-franceconnect.fr/session/end",
    statusURL: "https://fip1-high.docker.dev-franceconnect.fr/",
    jwksURL: "https://fip1-high.docker.dev-franceconnect.fr/jwks",
    authzURL: "https://fip1-high.docker.dev-franceconnect.fr/authorize",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip4-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 4,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "RSA-OAEP",
    userinfo_encrypted_response_enc: "A256GCM",
    amr: ["fc", "pwd"],
  },
  // -- FIP - FIP5-HIGH - Activated and invisible
  // use fip1 urls to avoid the generation of a container
  "FIP5-HIGH": {
    uid: "3ae390ce-c9b8-4090-926f-3db90f85fe6a",
    name: "fip5-active-invisible",
    active: true,
    display: false,
    isBeta: false,
    title: "FIP5 - FI activé et invisible",
    image: "",
    imageFocus: "",
    alt: "FIP5 - FI activé et invisible",
    trustedIdentity: false,
    eidas: 3,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip5-high",
    url: "https://fip1-high.docker.dev-franceconnect.fr",
    tokenURL: "https://fip1-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip1-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL: "https://fip1-high.docker.dev-franceconnect.fr/session/end",
    statusURL: "https://fip1-high.docker.dev-franceconnect.fr/",
    jwksURL: "https://fip1-high.docker.dev-franceconnect.fr/jwks",
    authzURL: "https://fip1-high.docker.dev-franceconnect.fr/authorize",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip5-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 5,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "RSA-OAEP",
    userinfo_encrypted_response_enc: "A256GCM",
    amr: ["fc", "pwd"],
  },
  // -- FIP - FIP6-HIGH
  "FIP6-HIGH": {
    uid: "2031310b-186e-4643-944a-00efb9d59e0f",
    name: "fip6-high",
    active: true,
    display: true,
    isBeta: false,
    title:
      "IDP6 - Identity Provider - eIDAS élevé - whitelisted - nodiscov - crypt",
    image: "",
    imageFocus: "",
    alt: "IDP6 - Identity Provider - eIDAS élevé - whitelisted - nodiscov - crypt",
    trustedIdentity: false,
    eidas: 3,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip6-high",
    url: "https://fip6-high.docker.dev-franceconnect.fr",
    tokenURL: "https://fip6-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip6-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL: "https://fip6-high.docker.dev-franceconnect.fr/session/end",
    statusURL: "https://fip6-high.docker.dev-franceconnect.fr/",
    jwksURL: "https://fip6-high.docker.dev-franceconnect.fr/jwks",
    authzURL: "https://fip6-high.docker.dev-franceconnect.fr/authorize",
    discovery: false,
    response_types: ["code"],
    clientID: "69a1a257648c1742c74d6a3d84b31943",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 6,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "RSA-OAEP",
    userinfo_encrypted_response_enc: "A256GCM",
    amr: ["fc", "pwd"],
  },
  // -- FIP - FIP7-HIGH - no discovery attribute
  // use fip1 urls to avoid the generation of a container
  "FIP7-HIGH": {
    uid: "ed928691-4697-44b4-9e56-df1853876610",
    name: "fip7-high",
    active: true,
    display: true,
    isBeta: false,
    title:
      "IDP7 - Identity Provider - eIDAS élevé - blacklisted - discov - nocrypt",
    image: "",
    imageFocus: "",
    alt: "IDP7 - Identity Provider - eIDAS élevé - blacklisted - discov - nocrypt",
    trustedIdentity: false,
    eidas: 3,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip7-high",
    url: "https://fip1-high.docker.dev-franceconnect.fr",
    statusURL: "https://fip1-high.docker.dev-franceconnect.fr/",
    // discovery: true,
    discoveryUrl:
      "https://fip1-high.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    response_types: ["code"],
    clientID: "79a1a257648c1742c74d6a3d84b31943",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 7,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    amr: ["fc", "pwd"],
  },
  // -- FIP - FIP8-HIGH - blacklisted
  // use fip1 urls to avoid the generation of a container
  // Blacklisted by FSP2
  // Absent of FSP5 whitelist
  "FIP8-HIGH": {
    uid: "0cbdf732-aaea-4566-a99e-4430f388ff18",
    name: "fip8-high",
    active: true,
    display: true,
    isBeta: false,
    title:
      "IDP8 - Identity Provider - eIDAS élevé - whitelisted - discov - crypt",
    image: "",
    imageFocus: "",
    alt: "IDP8 - Identity Provider - eIDAS élevé - whitelisted - discov - crypt",
    trustedIdentity: false,
    eidas: 3,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip8-high",
    url: "https://fip1-high.docker.dev-franceconnect.fr",
    statusURL: "https://fip1-high.docker.dev-franceconnect.fr/",
    discovery: true,
    discoveryUrl:
      "https://fip1-high.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    response_types: ["code"],
    clientID: "09a1a257648c1742c74d6a3d84b31943",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 8,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP-256",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "RSA-OAEP-256",
    userinfo_encrypted_response_enc: "A256GCM",
    amr: ["fc", "pwd"],
  },
  // -- FIP - FIP9-HIGH - no discovery url
  // use fip1 urls to avoid the generation of a container
  "FIP9-HIGH": {
    uid: "b4ae876d-773c-4b4a-bd45-33e0938af4a7",
    name: "fip9-high",
    active: true,
    display: true,
    isBeta: false,
    title:
      "IDP9 - Identity Provider - eIDAS élevé - whitelisted - discov - crypt",
    image: "",
    imageFocus: "",
    alt: "IDP9 - Identity Provider - eIDAS élevé - whitelisted - discov - crypt",
    trustedIdentity: false,
    eidas: 3,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip9-high",
    url: "https://fip1-high.docker.dev-franceconnect.fr",
    statusURL: "https://fip1-high.docker.dev-franceconnect.fr/",
    discovery: true,
    // discoveryUrl:
    //  "https://fip1-high.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    response_types: ["code"],
    clientID: "09a1a257648c1742c74d6a3d84b31943",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 9,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP-256",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "RSA-OAEP-256",
    userinfo_encrypted_response_enc: "A256GCM",
    amr: ["fc", "pwd"],
  },
  // -- FIP - FIP10-HIGH - invalid parameter
  // use fip1 urls to avoid the generation of a container
  "FIP10-HIGH": {
    uid: "a97369fb-f7b0-478a-bcc1-6fa49c8782d9",
    name: "fip10-high",
    active: true,
    display: true,
    isBeta: false,
    title:
      "IDP10 - Identity Provider - eIDAS élevé - whitelisted - discov - crypt",
    image: "",
    imageFocus: "",
    alt: "IDP10 - Identity Provider - eIDAS élevé - whitelisted - discov - crypt",
    trustedIdentity: false,
    eidas: 3,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip10-high",
    url: "https://fip1-high.docker.dev-franceconnect.fr",
    statusURL: "https://fip1-high.docker.dev-franceconnect.fr/",
    discovery: true,
    discoveryUrl:
      "https://fip1-high.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    // Invalid parameter when using discovery, for testing purpose
    authzURL: "https://fip1-high.docker.dev-franceconnect.fr/user/authorize",
    response_types: ["code"],
    clientID: "09a1a257648c1742c74d6a3d84b31943",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 10,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "RS256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP-256",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "RS256",
    userinfo_encrypted_response_alg: "RSA-OAEP-256",
    userinfo_encrypted_response_enc: "A256GCM",
    amr: ["fc", "pwd"],
  },
  // -- FIP - FIP11-HIGH
  // use fip1 urls to avoid the generation of a container
  "FIP11-HIGH": {
    uid: "a437f8aa-10b5-48bd-8931-78f2d055e3df",
    name: "fip11-high",
    active: true,
    display: true,
    isBeta: false,
    title:
      "IDP11 - Identity Provider - eIDAS élevé - whitelisted - nodiscov - crypt",
    image: "",
    imageFocus: "",
    alt: "IDP11 - Identity Provider - eIDAS élevé - whitelisted - nodiscov - crypt",
    trustedIdentity: false,
    eidas: 3,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip11-high",
    url: "https://fip1-high.docker.dev-franceconnect.fr",
    tokenURL: "https://fip1-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip1-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL: "https://fip1-high.docker.dev-franceconnect.fr/session/end",
    statusURL: "https://fip1-high.docker.dev-franceconnect.fr/",
    jwksURL: "https://fip1-high.docker.dev-franceconnect.fr/jwks",
    authzURL: "https://fip1-high.docker.dev-franceconnect.fr/authorize",
    discovery: false,
    response_types: ["code"],
    clientID: "09a1a257648c1742c74d6a3d84b31943",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 11,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "RS256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAE256",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "RS256",
    userinfo_encrypted_response_alg: "RSA-OAEP-256",
    userinfo_encrypted_response_enc: "A256GCM",
    amr: ["fc", "pwd"],
  },
  // -- FIP - IDP12-HIGH - Identity Provider not respecting the DTO
  // use fip1 urls to avoid the generation of a container
  "FIP12-HIGH": {
    uid: "7f90ea0f-b965-4f10-bbf8-d6ad19a17451",
    name: "fip12-high",
    active: true,
    display: true,
    isBeta: false,
    title:
      "IDP12 - Identity Provider - eIDAS élevé - crypted (ECDH-ES + A256GCM) - signed (ES256)",
    image: "",
    imageFocus: "",
    alt: "IDP12 - Identity Provider - eIDAS élevé - crypted (ECDH-ES + A256GCM) - signed (ES256)",
    trustedIdentity: false,
    eidas: 3,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip12-high",
    url: "https://fip1-high.docker.dev-franceconnect.fr",
    tokenURL: "https://fip1-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip1-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL: "https://fip1-high.docker.dev-franceconnect.fr/session/end",
    statusURL: "https://fip1-high.docker.dev-franceconnect.fr/",
    jwksURL: "https://fip1-high.docker.dev-franceconnect.fr/jwks",
    // Remove the authorize to not pass the DTO for tests purposes
    // authzURL: "https://fip1-high.docker.dev-franceconnect.fr/authorize",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip13-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 12,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "ECDH-ES",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "ECDH-ES",
    userinfo_encrypted_response_enc: "A256GCM",
    amr: ["fc", "pwd"],
  },
  // -- FIP - FIP13V2 - Activated - eIDAS élevé - crypted (ECDH-ES + A256GCM) - signed (ES256)
  "FIP13-HIGH": {
    uid: "8456c460-f89b-4744-93cf-e0b6ac694075",
    name: "fip13-high",
    active: true,
    display: true,
    isBeta: false,
    title:
      "IDP13 - Identity Provider - eIDAS élevé - crypted (ECDH-ES + A256GCM) - signed (ES256)",
    image: "",
    imageFocus: "",
    alt: "impots",
    trustedIdentity: false,
    eidas: 3,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip13-high",
    url: "https://fip13-high.docker.dev-franceconnect.fr",
    tokenURL: "https://fip13-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip13-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL: "https://fip13-high.docker.dev-franceconnect.fr/session/end",
    statusURL: "https://fip13-high.docker.dev-franceconnect.fr/",
    jwksURL: "https://fip13-high.docker.dev-franceconnect.fr/jwks",
    authzURL: "https://fip13-high.docker.dev-franceconnect.fr/authorize",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip13-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 13,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "ECDH-ES",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "ECDH-ES",
    userinfo_encrypted_response_enc: "A256GCM",
    amr: ["fc", "pwd"],
  },

  // -- FIP - FIP13V2BIS - Activated - INVALID FORMAT
  "FIP13BIS-HIGH": {
    uid: "ad0ed11b-621b-45e9-af75-64f27ced6d52",
    name: "fip13-high",
    active: true,
    display: true,
    isBeta: false,
    title: "IDP13 - Identity Provider - INVALID FORMAT",
    image: "",
    imageFocus: "",
    alt: "impots",
    trustedIdentity: false,
    eidas: 3,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip13-high",
    discovery: true,
    response_types: ["code"],
    clientID: "myclientidforfip13bis-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 13,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    userinfo_encrypted_response_alg: "ECDH-ES",
    userinfo_encrypted_response_enc: "A256GCM",
    amr: ["fc", "pwd"],
  },

  // -- FIP - FIP14V2 - Activated - eIDAS élevé - crypted (RSA-OAEP + A256GCM) - signed (RS256)
  "FIP14-HIGH": {
    uid: "81e3c37a-e7ea-43be-aa7a-0ed28a1a6e47",
    name: "fip14-high",
    active: true,
    display: true,
    isBeta: false,
    title:
      "IDP14 - Identity Provider - eIDAS élevé - crypted (RSA-OAEP + A256GCM) - signed (RS256)",
    image: "",
    imageFocus: "",
    alt: "impots",
    trustedIdentity: false,
    eidas: 3,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip14-high",
    url: "https://fip14-high.docker.dev-franceconnect.fr",
    statusURL: "https://fip14-high.docker.dev-franceconnect.fr/",
    authzURL: "https://fip14-high.docker.dev-franceconnect.fr/authorize",
    tokenURL: "https://fip14-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip14-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL: "https://fip14-high.docker.dev-franceconnect.fr/session/end",
    jwksURL: "https://fip14-high.docker.dev-franceconnect.fr/jwks",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip14-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 14,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "RS256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "RS256",
    userinfo_encrypted_response_alg: "RSA-OAEP",
    userinfo_encrypted_response_enc: "A256GCM",
    amr: ["fc", "pwd"],
  },

  // -- FIP - FIP15V2 - Activated - eIDAS substantiel - crypted (RSA-OAEP + A256GCM) - signed (ES256)
  "FIP15-HIGH": {
    uid: "4c3e8c0d-12e3-46c2-bef8-5cb7b0702c9d",
    name: "fip15-high",
    active: true,
    display: true,
    isBeta: false,
    title:
      "IDP15 - Identity Provider - eIDAS substantiel - crypted (RSA-OAEP + A256GCM) - signed (ES256)",
    image: "fi-mock-substantiel.svg",
    imageFocus: "fi-mock-substantiel.svg",
    alt: "impots",
    trustedIdentity: false,
    eidas: 2,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip15-high",
    url: "https://fip15-high.docker.dev-franceconnect.fr",
    statusURL: "https://fip15-high.docker.dev-franceconnect.fr/",
    authzURL: "https://fip15-high.docker.dev-franceconnect.fr/authorize",
    tokenURL: "https://fip15-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip15-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL: "https://fip15-high.docker.dev-franceconnect.fr/session/end",
    jwksURL: "https://fip15-high.docker.dev-franceconnect.fr/jwks",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip15-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 15,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    endSessionURL: "https://fip15-high.docker.dev-franceconnect.fr/session/end",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "RSA-OAEP",
    userinfo_encrypted_response_enc: "A256GCM",
    amr: ["fc", "pwd"],
  },

  // -- FIP - FIP16V2 - Activated - eIDAS substantiel - crypted (ECDH-ES + A256GCM) - signed (RS256)
  "FIP16-HIGH": {
    uid: "f403044b-fcd3-46f2-a87b-30e65f8e7bfe",
    name: "fip16-high",
    active: true,
    display: true,
    isBeta: false,
    title:
      "IDP16 - Identity Provider - eIDAS substantiel - crypted (ECDH-ES + A256GCM) - signed (RS256)",
    image: "",
    imageFocus: "",
    alt: "impots",
    trustedIdentity: false,
    eidas: 2,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip16-high",
    url: "https://fip16-high.docker.dev-franceconnect.fr",
    statusURL: "https://fip16-high.docker.dev-franceconnect.fr/",
    authzURL: "https://fip16-high.docker.dev-franceconnect.fr/authorize",
    tokenURL: "https://fip16-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip16-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL: "https://fip16-high.docker.dev-franceconnect.fr/session/end",
    jwksURL: "https://fip16-high.docker.dev-franceconnect.fr/jwks",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip16-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 16,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "RS256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "ECDH-ES",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "RS256",
    userinfo_encrypted_response_alg: "ECDH-ES",
    userinfo_encrypted_response_enc: "A256GCM",
    amr: ["fc", "pwd"],
  },

  // -- FIP - FIP17V2 - Activated - eIDAS substantiel - crypted (none) - signed (ES256)
  "FIP17-HIGH": {
    uid: "913ef56e-0997-4e25-bc55-19a20d6e0532",
    name: "fip17-high",
    active: true,
    display: true,
    isBeta: false,
    title:
      "IDP17 - Identity Provider - eIDAS substantiel - crypted (none) - signed (ES256)",
    image: "",
    imageFocus: "",
    alt: "impots",
    trustedIdentity: false,
    eidas: 2,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip17-high",
    url: "https://fip17-high.docker.dev-franceconnect.fr",
    authzURL: "https://fip17-high.docker.dev-franceconnect.fr/authorize",
    tokenURL: "https://fip17-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip17-high.docker.dev-franceconnect.fr/userinfo",
    statusURL: "https://fip17-high.docker.dev-franceconnect.fr/",
    endSessionURL: "https://fip17-high.docker.dev-franceconnect.fr/session/end",
    jwksURL: "https://fip17-high.docker.dev-franceconnect.fr/jwks",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip17-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 17,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    amr: ["fc", "pwd"],
  },

  // -- FIP - FIP18V2 - Activated - eIDAS faible - crypted (none) - signed (ES256)
  "FIP18-HIGH": {
    uid: "c341093a-f4b4-4151-85ff-5fbdcd6baa58",
    name: "fip18-high",
    active: true,
    display: true,
    isBeta: false,
    title:
      "IDP18 - Identity Provider - eIDAS faible - crypted (none) - signed (ES256)",
    image: "fi-mock-faible.svg",
    imageFocus: "fi-mock-faible.svg",
    alt: "impots",
    trustedIdentity: false,
    eidas: 1,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip18-high",
    url: "https://fip18-high.docker.dev-franceconnect.fr",
    statusURL: "https://fip18-high.docker.dev-franceconnect.fr/",
    authzURL: "https://fip18-high.docker.dev-franceconnect.fr/authorize",
    tokenURL: "https://fip18-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip18-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL: "https://fip18-high.docker.dev-franceconnect.fr/session/end",
    jwksURL: "https://fip18-high.docker.dev-franceconnect.fr/jwks",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip18-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 18,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    amr: ["fc", "pwd"],
  },

  // -- FIP - FIP19V2 - Activated - eIDAS faible - crypted (none) - signed (RS256)
  "FIP19-HIGH": {
    uid: "3c8776ae-5278-425b-8e97-7f01eadd22a0",
    name: "fip19-high",
    active: true,
    display: true,
    isBeta: false,
    title:
      "IDP19 - Identity Provider - eIDAS faible - crypted (none) - signed (RS256)",
    image: "",
    imageFocus: "",
    alt: "impots",
    trustedIdentity: false,
    eidas: 1,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip19-high",
    url: "https://fip19-high.docker.dev-franceconnect.fr",
    statusURL: "https://fip19-high.docker.dev-franceconnect.fr/",
    authzURL: "https://fip19-high.docker.dev-franceconnect.fr/authorize",
    tokenURL: "https://fip19-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip19-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL: "https://fip19-high.docker.dev-franceconnect.fr/session/end",
    jwksURL: "https://fip19-high.docker.dev-franceconnect.fr/jwks",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip19-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 19,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "RS256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "RS256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    amr: ["fc", "pwd"],
  },

  // -- FIP - FIP20V2 - Activated - eIDAS faible - crypted (none) - signed (HS256)
  "FIP20-HIGH": {
    uid: "7d35f733-a3d0-49c1-9a6f-b9f4800b0b7a",
    name: "fip20-high",
    active: true,
    display: true,
    isBeta: false,
    title:
      "IDP20 - Identity Provider - eIDAS faible - crypted (none) - signed (HS256)",
    image: "",
    imageFocus: "",
    alt: "impots",
    trustedIdentity: false,
    eidas: 1,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip20-high",
    url: "https://fip20-high.docker.dev-franceconnect.fr",
    statusURL: "https://fip20-high.docker.dev-franceconnect.fr/",
    authzURL: "https://fip20-high.docker.dev-franceconnect.fr/authorize",
    tokenURL: "https://fip20-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip20-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL: "https://fip20-high.docker.dev-franceconnect.fr/session/end",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip20-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 20,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "HS256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "HS256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    amr: ["fc", "pwd"],
  },
  // -- FIP - FIP21-HIGH - BETA
  "FIP21-HIGH": {
    uid: "de28e362-b476-41dc-9c6d-fadb3a21d871",
    name: "fip21-high",
    active: true,
    display: true,
    isBeta: true,
    title: "IDP21 - Identity Provider - eIDAS élevé - nodiscov - crypt - beta",
    image: "",
    imageFocus: "",
    alt: "IDP21 - Identity Provider - eIDAS élevé - nodiscov - crypt - beta",
    trustedIdentity: false,
    eidas: 3,
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
    },
    mailto: "",
    specificText: "specific text fip21-high",
    url: "https://fip21-high.docker.dev-franceconnect.fr",
    tokenURL: "https://fip21-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip21-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL: "https://fip21-high.docker.dev-franceconnect.fr/session/end",
    statusURL: "https://fip21-high.docker.dev-franceconnect.fr/",
    jwksURL: "https://fip21-high.docker.dev-franceconnect.fr/jwks",
    authzURL: "https://fip21-high.docker.dev-franceconnect.fr/authorize",
    discovery: false,
    response_types: ["code"],
    clientID: "09a1a2576d8c1742c74d6as3d84b31943",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 21,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "RSA-OAEP",
    userinfo_encrypted_response_enc: "A256GCM",
    amr: ["fc", "pwd"],
  },

  // -- FIPEIDAS - FIPEIDASV2 - Activated
  EIDASBRIDGE: {
    uid: "8aa849db-8402-4f2e-bad9-7471dd21ff94",
    url: "https://eidas-bridge.docker.dev-franceconnect.fr",
    name: "eidas-bridge",
    image: "demonstration_eleve.png",
    title: "eIDAS Identity Provider",
    active: true,
    display: true,
    isBeta: false,
    featureHandlers: {
      coreVerify: "core-fcp-eidas-verify",
      authenticationEmail: null,
      idpIdentityCheck: "core-fcp-eidas-identity-check",
    },
    clientID: "myclientidforeidas-bridge-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    response_types: ["code"],
    revocation_endpoint_auth_method: "client_secret_post",
    discovery: false,
    authzURL: "https://eidas-bridge.docker.dev-franceconnect.fr/authorize",
    tokenURL: "https://eidas-bridge.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://eidas-bridge.docker.dev-franceconnect.fr/userinfo",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "RSA-OAEP",
    userinfo_encrypted_response_enc: "A256GCM",
    id_token_signed_response_alg: "ES256",
    id_token_encrypted_response_alg: "RSA-OAEP",
    id_token_encrypted_response_enc: "A256GCM",
    token_endpoint_auth_method: "client_secret_post",
    jwksURL: "https://eidas-bridge.docker.dev-franceconnect.fr/jwks",

    // metadata
    imageFocus: "demonstration_eleve_hover.png",
    alt: "impots",
    trustedIdentity: false,
    eidas: 3,
    mailto: "",
    specificText: "specific text fip1-high",
    // order set at 99: to avoid to change every time a new FI is added
    order: 99,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    endSessionURL:
      "https://eidas-bridge.docker.dev-franceconnect.fr/session/end",
    statusURL: "https://eidas-bridge.docker.dev-franceconnect.fr/",
    amr: ["eidas"],
  },
};

// -- FIs ----------

Object.values(fip).forEach((fi) => {
  print(`FIP > Initializing provider: ${fi.name} - Activated`);
  db.provider.update({ uid: fi.uid }, fi, { upsert: true });
});
