// == FI
const BASE_DEV_IDP_HIGH = {
  modal: {
    active: false,
    title: "",
    body: "",
    continueText: "",
    moreInfoLabel: "",
    moreInfoUrl: "",
  },
};

const fip = {
  // FIP1-HIGH - eidas3, RSA-OAEP-256 and Discovery
  "FIP1-HIGH": {
    uid: "dedc7160-8811-4d0f-9dd7-c072c15f2f18",
    name: "fip1-high",
    active: true,
    display: true,
    isBeta: false,
    title: "FIP1 - eIDAS élevé - RSA - discov",
    image: "fi-mock-eleve.svg",
    imageFocus: "fi-mock-eleve.svg",
    alt: "FIP1 - eIDAS élevé - RSA - discov",
    trustedIdentity: false,
    eidas: 3,
    allowedAcr: ["eidas2", "eidas3"],
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
      coreAuthorization: "core-fcp-default-authorization",
    },
    mailto: "",
    specificText: "specific text fip1-high",
    url: "https://fip1-high.docker.dev-franceconnect.fr",
    discovery: true,
    discoveryUrl:
      "https://fip1-high.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    response_types: ["code"],
    clientID: "09a1a257648c1742c74d6a3d84b31943",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 1,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP-256",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "RSA-OAEP-256",
    userinfo_encrypted_response_enc: "A256GCM",
    amr: ["fc", "pop", "pin", "mfa"],
  },
  // FIP2-HIGH - eidas3, ECDH-ES, no discovery, no endSessionURL
  "FIP2-HIGH": {
    uid: "f9a3f6fe-f9b3-4cec-b787-33713fdffc79",
    name: "fip2-high",
    active: true,
    display: true,
    isBeta: false,
    title: "FIP2 - eIDAS élevé - EC - nodiscov",
    image: "fi-mock-eleve.svg",
    imageFocus: "fi-mock-eleve.svg",
    alt: "FIP2 - eIDAS élevé - EC - nodiscov",
    trustedIdentity: false,
    eidas: 3,
    allowedAcr: ["eidas2", "eidas3"],
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
      coreAuthorization: "core-fcp-default-authorization",
    },
    mailto: "",
    specificText: "specific text fip2-high",
    url: "https://fip2-high.docker.dev-franceconnect.fr",
    tokenURL: "https://fip2-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip2-high.docker.dev-franceconnect.fr/userinfo",
    // endSessionURL: "https://fip2-high.docker.dev-franceconnect.fr/session/end",
    statusURL: "https://fip2-high.docker.dev-franceconnect.fr/",
    jwksURL: "https://fip2-high.docker.dev-franceconnect.fr/jwks",
    authzURL: "https://fip2-high.docker.dev-franceconnect.fr/authorize",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip2-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 2,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "RS256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "ECDH-ES",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "RS256",
    userinfo_encrypted_response_alg: "ECDH-ES",
    userinfo_encrypted_response_enc: "A256GCM",
    amr: ["fc", "pwd", "mail"],
  },
  // FIP3-HIGH - eidas2, RSA-OAEP-256 and no discovery
  "FIP3-HIGH": {
    uid: "4c3e8c0d-12e3-46c2-bef8-5cb7b0702c9d",
    name: "fip3-high",
    active: true,
    display: true,
    isBeta: false,
    title:
      "FIP3 - eIDAS substantiel - RSA - nodiscov",
    image: "fi-mock-substantiel.svg",
    imageFocus: "fi-mock-substantiel.svg",
    alt: "FIP3 - eIDAS substantiel - RSA - nodiscov",
    trustedIdentity: false,
    eidas: 2,
    allowedAcr: ["eidas2"],
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
      coreAuthorization: "core-fcp-default-authorization",
    },
    mailto: "",
    specificText: "specific text fip3-high",
    url: "https://fip3-high.docker.dev-franceconnect.fr",
    statusURL: "https://fip3-high.docker.dev-franceconnect.fr/",
    authzURL: "https://fip3-high.docker.dev-franceconnect.fr/authorize",
    tokenURL: "https://fip3-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip3-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL: "https://fip3-high.docker.dev-franceconnect.fr/session/end",
    jwksURL: "https://fip3-high.docker.dev-franceconnect.fr/jwks",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip3-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 3,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP-256",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "RSA-OAEP-256",
    userinfo_encrypted_response_enc: "A256GCM",
    amr: ["fc", "pwd"],
  },
  // FIP4-HIGH - eidas2, Beta and no encoding
  "FIP4-HIGH": {
    uid: "34962c29-23a3-4748-8913-1875d3d424f2",
    name: "fip4-high",
    active: true,
    display: true,
    isBeta: true,
    title:
      "FIP4 - eIDAS substantiel - beta - nodiscov - no crypt",
    image: "fi-mock-substantiel.svg",
    imageFocus: "fi-mock-substantiel.svg",
    alt: "FIP4 - eIDAS substantiel - beta - nodiscov - no crypt",
    trustedIdentity: false,
    eidas: 2,
    allowedAcr: ["eidas2"],
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
      coreAuthorization: "core-fcp-default-authorization",
    },
    mailto: "",
    specificText: "specific text fip4-high",
    url: "https://fip4-high.docker.dev-franceconnect.fr",
    tokenURL: "https://fip4-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip4-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL: "https://fip4-high.docker.dev-franceconnect.fr/session/end",
    statusURL: "https://fip4-high.docker.dev-franceconnect.fr/",
    jwksURL: "https://fip4-high.docker.dev-franceconnect.fr/jwks",
    authzURL: "https://fip4-high.docker.dev-franceconnect.fr/authorize",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip4-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 4,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "RS256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "RS256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    amr: ["fc", "pwd"],
  },
  // FIP5-HIGH - eidas3 only
  "FIP5-HIGH": {
    uid: "0380ac4f-e07e-4496-bcde-d5eac12e9049",
    name: "fip5-high",
    active: true,
    display: true,
    isBeta: false,
    title:
      "FIP5 - eIDAS élevé - eidas3 seulement",
    image: "fi-mock-eleve.svg",
    imageFocus: "fi-mock-eleve.svg",
    alt: "FIP5 - eIDAS élevé - eidas3 seulement",
    trustedIdentity: false,
    eidas: 3,
    allowedAcr: ["eidas3"],
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
      coreAuthorization: "core-fcp-default-authorization",
    },
    mailto: "",
    specificText: "specific text fip5-high",
    url: "https://fip5-high.docker.dev-franceconnect.fr",
    tokenURL: "https://fip5-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip5-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL: "https://fip5-high.docker.dev-franceconnect.fr/session/end",
    statusURL: "https://fip5-high.docker.dev-franceconnect.fr/",
    jwksURL: "https://fip5-high.docker.dev-franceconnect.fr/jwks",
    authzURL: "https://fip5-high.docker.dev-franceconnect.fr/authorize",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip5-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 5,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "RS256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP-256",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "RS256",
    userinfo_encrypted_response_alg: "RSA-OAEP-256",
    userinfo_encrypted_response_enc: "A256GCM",
    amr: ["fc", "pop", "pin", "mfa"],
  },

  /**
   * FIs without container (using fip1-high urls) for specific states
   * With name above FIP50-HIGH
   */

  // FIP51-HIGH - Invalid format - Missing discovery attribute
  "FIP51-HIGH": {
    uid: "ed928691-4697-44b4-9e56-df1853876610",
    name: "fip51-high",
    active: true,
    display: true,
    isBeta: false,
    title:
      "FIP51 - Mauvais Format - Attribut discovery manquant",
    image: "",
    imageFocus: "",
    alt: "FIP51 - Mauvais Format - Attribut discovery manquant",
    trustedIdentity: false,
    eidas: 3,
    allowedAcr: ["eidas2", "eidas3"],
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
      coreAuthorization: "core-fcp-default-authorization",
    },
    mailto: "",
    specificText: "specific text fip7-high",
    url: "https://fip1-high.docker.dev-franceconnect.fr",
    statusURL: "https://fip1-high.docker.dev-franceconnect.fr/",
    // discovery: true,
    discoveryUrl:
      "https://fip1-high.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    response_types: ["code"],
    clientID: "79a1a257648c1742c74d6a3d84b31943",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 51,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    amr: ["fc", "pwd"],
  },
  // FIP52-HIGH - invalid authzURL parameter when using discovery
  "FIP52-HIGH": {
    uid: "a97369fb-f7b0-478a-bcc1-6fa49c8782d9",
    name: "fip52-high",
    active: true,
    display: true,
    isBeta: false,
    title:
      "FIP52 - Mauvais Format - Attribut authzURL avec discovery",
    image: "",
    imageFocus: "",
    alt: "FIP52 - Mauvais Format - Attribut authzURL avec discovery",
    trustedIdentity: false,
    eidas: 3,
    allowedAcr: ["eidas2", "eidas3"],
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
      coreAuthorization: "core-fcp-default-authorization",
    },
    mailto: "",
    specificText: "specific text fip10-high",
    url: "https://fip1-high.docker.dev-franceconnect.fr",
    statusURL: "https://fip1-high.docker.dev-franceconnect.fr/",
    discovery: true,
    discoveryUrl:
      "https://fip1-high.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    // Invalid parameter when using discovery, for testing purpose
    authzURL: "https://fip1-high.docker.dev-franceconnect.fr/user/authorize",
    response_types: ["code"],
    clientID: "09a1a257648c1742c74d6a3d84b31943",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 52,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "RS256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP-256",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "RS256",
    userinfo_encrypted_response_alg: "RSA-OAEP-256",
    userinfo_encrypted_response_enc: "A256GCM",
    amr: ["fc", "pwd"],
  },
  // FIP53-HIGH - Deactivated but visible
  "FIP53-HIGH": {
    uid: "621c3c17-5f49-4ca5-b8ef-a4b1cecaf7c2",
    name: "fip53-desactive-visible",
    active: false,
    display: true,
    isBeta: false,
    title: "FIP53 - FI désactivé mais visible",
    image: "",
    imageFocus: "",
    alt: "FIP53 - FI désactivé mais visible",
    trustedIdentity: false,
    eidas: 3,
    allowedAcr: ["eidas2", "eidas3"],
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
      coreAuthorization: "core-fcp-default-authorization",
    },
    mailto: "",
    specificText: "specific text fip3-high",
    url: "https://fip1-high.docker.dev-franceconnect.fr",
    tokenURL: "https://fip1-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip1-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL: "https://fip1-high.docker.dev-franceconnect.fr/session/end",
    statusURL: "https://fip1-high.docker.dev-franceconnect.fr/",
    jwksURL: "https://fip1-high.docker.dev-franceconnect.fr/jwks",
    authzURL: "https://fip1-high.docker.dev-franceconnect.fr/authorize",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip53-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 53,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP-256",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "RSA-OAEP-256",
    userinfo_encrypted_response_enc: "A256GCM",
    amr: ["fc", "pwd", "mail"],
  },
  // FIP54-HIGH - Deactivated and invisible
  "FIP54-HIGH": {
    uid: "ce0f6c4d-d70e-411e-a8a0-2a66afa7bd90",
    name: "fip54-desactive-invisible",
    active: false,
    display: false,
    isBeta: false,
    title: "FIP54 - FI désactivé et invisible",
    image: "",
    imageFocus: "",
    alt: "FIP54 - FI désactivé et invisible",
    trustedIdentity: false,
    eidas: 3,
    allowedAcr: ["eidas2", "eidas3"],
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
      coreAuthorization: "core-fcp-default-authorization",
    },
    mailto: "",
    specificText: "specific text fip4-high",
    url: "https://fip1-high.docker.dev-franceconnect.fr",
    tokenURL: "https://fip1-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip1-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL: "https://fip1-high.docker.dev-franceconnect.fr/session/end",
    statusURL: "https://fip1-high.docker.dev-franceconnect.fr/",
    jwksURL: "https://fip1-high.docker.dev-franceconnect.fr/jwks",
    authzURL: "https://fip1-high.docker.dev-franceconnect.fr/authorize",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip54-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 54,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP-256",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "RSA-OAEP-256",
    userinfo_encrypted_response_enc: "A256GCM",
    amr: ["fc", "pwd"],
  },
  // FIP55-HIGH - Activated and invisible
  "FIP55-HIGH": {
    uid: "3ae390ce-c9b8-4090-926f-3db90f85fe6a",
    name: "fip55-active-invisible",
    active: true,
    display: false,
    isBeta: false,
    title: "FIP5 - FI activé et invisible",
    image: "",
    imageFocus: "",
    alt: "FIP5 - FI activé et invisible",
    trustedIdentity: false,
    eidas: 3,
    allowedAcr: ["eidas2", "eidas3"],
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
      coreAuthorization: "core-fcp-default-authorization",
    },
    mailto: "",
    specificText: "specific text fip5-high",
    url: "https://fip1-high.docker.dev-franceconnect.fr",
    tokenURL: "https://fip1-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip1-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL: "https://fip1-high.docker.dev-franceconnect.fr/session/end",
    statusURL: "https://fip1-high.docker.dev-franceconnect.fr/",
    jwksURL: "https://fip1-high.docker.dev-franceconnect.fr/jwks",
    authzURL: "https://fip1-high.docker.dev-franceconnect.fr/authorize",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip55-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 55,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP-256",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "RSA-OAEP-256",
    userinfo_encrypted_response_enc: "A256GCM",
    amr: ["fc", "pwd"],
  },
  // FIP56-HIGH - Blacklisted by FSP2 and Absent of FSP5 whitelist
  "FIP56-HIGH": {
    uid: "0cbdf732-aaea-4566-a99e-4430f388ff18",
    name: "fip56-high",
    active: true,
    display: true,
    isBeta: false,
    title:
      "FIP56 - Blacklisté par FSP2 et non whitelisté par FSP5",
    image: "",
    imageFocus: "",
    alt: "FIP56 - Blacklisté par FSP2 et non whitelisté par FSP5",
    trustedIdentity: false,
    eidas: 3,
    allowedAcr: ["eidas2", "eidas3"],
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
      coreAuthorization: "core-fcp-default-authorization",
    },
    mailto: "",
    specificText: "specific text fip56-high",
    url: "https://fip1-high.docker.dev-franceconnect.fr",
    statusURL: "https://fip1-high.docker.dev-franceconnect.fr/",
    discovery: true,
    discoveryUrl:
      "https://fip1-high.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    response_types: ["code"],
    clientID: "09a1a257648c1742c74d6a3d84b31943",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 56,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP-256",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "RSA-OAEP-256",
    userinfo_encrypted_response_enc: "A256GCM",
    amr: ["fc", "pwd"],
  },
  // FIP57-HIGH - Invalid format - Missing discoveryUrl attribute
  "FIP57-HIGH": {
    uid: "b4ae876d-773c-4b4a-bd45-33e0938af4a7",
    name: "fip57-high",
    active: true,
    display: true,
    isBeta: false,
    title:
      "FIP57 - Mauvais format - attribut discoveryUrl manquant",
    image: "",
    imageFocus: "",
    alt: "FIP57 - Mauvais format - attribut discoveryUrl manquant",
    trustedIdentity: false,
    eidas: 3,
    allowedAcr: ["eidas2", "eidas3"],
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
      coreAuthorization: "core-fcp-default-authorization",
    },
    mailto: "",
    specificText: "specific text fip9-high",
    url: "https://fip1-high.docker.dev-franceconnect.fr",
    statusURL: "https://fip1-high.docker.dev-franceconnect.fr/",
    discovery: true,
    // discoveryUrl:
    //  "https://fip1-high.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    response_types: ["code"],
    clientID: "09a1a257648c1742c74d6a3d84b31943",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 57,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP-256",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "RSA-OAEP-256",
    userinfo_encrypted_response_enc: "A256GCM",
    amr: ["fc", "pwd"],
  },
  // FIP58-HIGH - with user confirmation modal
  "FIP58-HIGH": {
    uid: "a437f8aa-10b5-48bd-8931-78f2d055e3df",
    name: "fip58-high",
    active: true,
    display: true,
    isBeta: false,
    title:
      "FIP58 - eIDAS élevé - avec modale",
    image: "",
    imageFocus: "",
    alt: "FIP58 - eIDAS élevé - avec modale",
    trustedIdentity: false,
    eidas: 3,
    allowedAcr: ["eidas2", "eidas3"],
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
      coreAuthorization: "core-fcp-default-authorization",
    },
    mailto: "",
    specificText: "specific text fip58-high",
    url: "https://fip1-high.docker.dev-franceconnect.fr",
    tokenURL: "https://fip1-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip1-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL: "https://fip1-high.docker.dev-franceconnect.fr/session/end",
    statusURL: "https://fip1-high.docker.dev-franceconnect.fr/",
    jwksURL: "https://fip1-high.docker.dev-franceconnect.fr/jwks",
    authzURL: "https://fip1-high.docker.dev-franceconnect.fr/authorize",
    discovery: false,
    response_types: ["code"],
    clientID: "09a1a257648c1742c74d6a3d84b31943",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 58,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "RSA-OAEP-256",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "RSA-OAEP-256",
    userinfo_encrypted_response_enc: "A256GCM",
    amr: ["fc", "pwd"],
    modal: {
      active: true,
      title: "Votre compte France Identité est-il certifié en mairie ?",
      body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at metus porttitor felis sollicitudin congue eget eu nulla. Pellentesque nec sem ac urna varius tempor cursus et diam. Aliquam mauris nulla, gravida ut bibendum ac, convallis eu magna. Nullam lobortis turpis nibh, pellentesque hendrerit velit ornare tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      continueText: "Oui, mon compte est certifié",
      moreInfoLabel: "En savoir plus",
      moreInfoUrl: "https://aide.franceconnect.gouv.fr/",
    },
  },
  // FIP59-HIGH - Invalid format - Missing authzURL attribute
  "FIP59-HIGH": {
    uid: "7f90ea0f-b965-4f10-bbf8-d6ad19a17451",
    name: "fip59-high",
    active: true,
    display: true,
    isBeta: false,
    title:
      "FIP59 - Mauvais format - attribut authzURL manquant",
    image: "",
    imageFocus: "",
    alt: "FIP59 - Mauvais format - attribut authzURL manquant",
    trustedIdentity: false,
    eidas: 3,
    allowedAcr: ["eidas2", "eidas3"],
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
      coreAuthorization: "core-fcp-default-authorization",
    },
    mailto: "",
    specificText: "specific text fip12-high",
    url: "https://fip1-high.docker.dev-franceconnect.fr",
    tokenURL: "https://fip1-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip1-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL: "https://fip1-high.docker.dev-franceconnect.fr/session/end",
    statusURL: "https://fip1-high.docker.dev-franceconnect.fr/",
    jwksURL: "https://fip1-high.docker.dev-franceconnect.fr/jwks",
    // Remove the authorize to not pass the DTO for tests purposes
    // authzURL: "https://fip1-high.docker.dev-franceconnect.fr/authorize",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip12-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 59,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "ECDH-ES",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "ECDH-ES",
    userinfo_encrypted_response_enc: "A256GCM",
    amr: ["fc", "pwd"],
  },
  // FIP60-HIGH - Invalid format - acr eidas1
  "FIP60-HIGH": {
    uid: "3c8776ae-5278-425b-8e97-7f01eadd22a0",
    name: "fip60-high",
    active: true,
    display: true,
    isBeta: false,
    title:
      "FIP60 - Mauvais format - acr eidas1",
    image: "",
    imageFocus: "",
    alt: "FIP60 - Mauvais format - acr eidas1",
    trustedIdentity: false,
    eidas: 1,
    allowedAcr: ["eidas1"],
    featureHandlers: {
      coreVerify: "core-fcp-default-verify",
      authenticationEmail: "core-fcp-send-email",
      idpIdentityCheck: "core-fcp-default-identity-check",
      coreAuthorization: "core-fcp-default-authorization",
    },
    mailto: "",
    specificText: "specific text fip19-high",
    url: "https://fip1-high.docker.dev-franceconnect.fr",
    statusURL: "https://fip1-high.docker.dev-franceconnect.fr/",
    authzURL: "https://fip1-high.docker.dev-franceconnect.fr/authorize",
    tokenURL: "https://fip1-high.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://fip1-high.docker.dev-franceconnect.fr/userinfo",
    endSessionURL: "https://fip1-high.docker.dev-franceconnect.fr/session/end",
    jwksURL: "https://fip1-high.docker.dev-franceconnect.fr/jwks",
    discovery: false,
    response_types: ["code"],
    clientID: "myclientidforfip60-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: 60,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    id_token_signed_response_alg: "RS256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "RS256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    amr: ["fc", "pwd"],
  },

  // FI for eidas-bridge testing
  EIDASBRIDGE: {
    uid: "8aa849db-8402-4f2e-bad9-7471dd21ff94",
    url: "https://eidas-bridge.docker.dev-franceconnect.fr",
    name: "eidas-bridge",
    image: "demonstration_eleve.png",
    title: "eIDAS Identity Provider",
    active: true,
    display: true,
    isBeta: false,
    featureHandlers: {
      coreVerify: "core-fcp-eidas-verify",
      authenticationEmail: null,
      idpIdentityCheck: "core-fcp-eidas-identity-check",
      coreAuthorization: "core-fcp-default-authorization",
    },
    clientID: "myclientidforeidas-bridge-high",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    response_types: ["code"],
    revocation_endpoint_auth_method: "client_secret_post",
    discovery: false,
    authzURL: "https://eidas-bridge.docker.dev-franceconnect.fr/authorize",
    tokenURL: "https://eidas-bridge.docker.dev-franceconnect.fr/token",
    userInfoURL: "https://eidas-bridge.docker.dev-franceconnect.fr/userinfo",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "RSA-OAEP",
    userinfo_encrypted_response_enc: "A256GCM",
    id_token_signed_response_alg: "ES256",
    id_token_encrypted_response_alg: "RSA-OAEP",
    id_token_encrypted_response_enc: "A256GCM",
    token_endpoint_auth_method: "client_secret_post",
    jwksURL: "https://eidas-bridge.docker.dev-franceconnect.fr/jwks",

    // metadata
    imageFocus: "demonstration_eleve_hover.png",
    alt: "impots",
    trustedIdentity: false,
    eidas: 3,
    allowedAcr: ["eidas2", "eidas3"],
    mailto: "",
    specificText: "specific text fip1-high",
    // order set at 99: to avoid to change every time a new FI is added
    order: 99,
    createdAt: new Date("2022-02-23 17:09:17"),
    updatedAt: new Date("2023-03-10 17:09:17"),
    updatedBy: "admin",
    endSessionURL:
      "https://eidas-bridge.docker.dev-franceconnect.fr/session/end",
    statusURL: "https://eidas-bridge.docker.dev-franceconnect.fr/",
    amr: ["eidas"],
  },
};

// -- FIs ----------

Object.values(fip).forEach((fi) => {
  print(`FIP > Initializing provider: ${fi.name} - Activated`);
  db.provider.updateOne(
    { uid: fi.uid },
    { $set: { ...BASE_DEV_IDP_HIGH, ...fi } },
    { upsert: true },
  );
});
