/* istanbul ignore file */

// Declarative code
export enum ErrorCode {
  CHECKTOKEN_TIMEOUT_EXCEPTION = 1,
  CHECKTOKEN_HTTP_STATUS_EXCEPTION = 2,
  JWKS_FETCH_FAILED_EXCEPTION = 3,
  CHECKTOKEN_INVALID_ALGORYTHM = 4,
  CHECKTOKEN_INVALID_ENCODING = 5,
}
