####################
####################
services:
  all-eidas-high:
    image: ${DOCKER_HUB_PROXY}alpine
    depends_on:
      - "all-fcp-high"
      - "eidas-bridge"
      - "eidas-fr"
      - "eidas-mock"
      - "eidas-be"
  min-eidas-high:
    image: ${DOCKER_HUB_PROXY}alpine
    depends_on:
      - "min-fcp-high"
      - "eidas-bridge"
      - "eidas-fr"
      - "eidas-mock"
      - "eidas-be"
  min-eidas-low:
    image: ${DOCKER_HUB_PROXY}alpine
    depends_on:
      - "min-fcp-low"
      - "eidas-bridge"
      - "eidas-fr"
      - "eidas-mock"
      - "eidas-be"
