export enum ErrorCode {
  LOW_ACR = 1,
  INVALID_ACR = 2,
  MISSING_IDENTITY = 4,
  FAILED_PERSISTENCE = 8,
  CLAIM_AMR = 9,
  IDENTITY_PROVIDER_NOT_FOUND = 10,
  CORE_IDP_BLOCKED_FOR_ACCOUNT = 11,
  IDENTITY_CHECK_TOKEN = 13,
  NOT_ALLOWED_ACR = 18,
  MISSING_AT_HASH = 19,
}
