version: "2.4"

####################
####################
services:
  mongo-fca-low:
    hostname: mongo-fca-low
    build:
      context: "${WORKING_DIR}"
      dockerfile: "${WORKING_DIR}/builds/mongodb/Dockerfile"
      args:
        MONGO_VERSION: "4.4"
    volumes:
      - "${VOLUMES_DIR}/mongo-fca-low/scripts:/opt/scripts"
      - "${VOLUMES_DIR}/mongo-fca-low/initdb.d:/docker-entrypoint-initdb.d"
    env_file:
      - "${COMPOSE_DIR}/fca-low/.env/mongo-fca-low.env"
    networks:
      - data
