export enum UserDashboardBackRoutes {
  USER_PREFERENCES = '/user-preferences',
  ERROR = '/error',
  LOGIN = '/login',
  LOGIN_CALLBACK = '/login-callback',
  LOGOUT = '/logout',
  LOGOUT_CALLBACK = '/logout-callback',
  REVOCATION = '/revocation',
  TRACKS = '/traces',
  USER_INFOS = '/me',
  VERIFY = '/interaction/:uid/verify',
  WELL_KNOWN_KEYS = '/.well-known/keys',
  CSRF_TOKEN = '/csrf-token',
  OIDC_CLIENT_GET_END_SESSION_URL = '/oidc-client/get-end-session-url',
}
