/* istanbul ignore file */

// declarative file
export enum ServiceProvidersActionTypes {
  SERVICE_PROVIDERS_REQUESTED = 'SERVICE_PROVIDERS_REQUESTED',
  SERVICE_PROVIDERS_SUCCESSED = 'SERVICE_PROVIDERS_SUCCESSED',
  SERVICE_PROVIDERS_FAILED = 'SERVICE_PROVIDERS_FAILED',
  SERVICE_PROVIDER_READ_REQUESTED = 'SERVICE_PROVIDER_READ_REQUESTED',
  SERVICE_PROVIDER_READ_SUCCESSED = 'SERVICE_PROVIDER_READ_SUCCESSED',
  SERVICE_PROVIDER_READ_FAILED = 'SERVICE_PROVIDER_READ_FAILED',
  SERVICE_PROVIDER_UPDATE_REQUESTED = 'SERVICE_PROVIDER_UPDATE_REQUESTED',
  SERVICE_PROVIDER_UPDATE_SUCCESSED = 'SERVICE_PROVIDER_UPDATE_SUCCESSED',
  SERVICE_PROVIDER_UPDATE_FAILED = 'SERVICE_PROVIDER_UPDATE_FAILED',
}
