/* istanbul ignore file */

// declarative file
export enum ServiceProviderViewActionTypes {
  SERVICE_PROVIDER_VIEW_REQUESTED = 'SERVICE_PROVIDER_VIEW_REQUESTED',
  SERVICE_PROVIDER_VIEW_SUCCESSED = 'SERVICE_PROVIDER_VIEW_SUCCESSED',
  SERVICE_PROVIDER_VIEW_FAILED = 'SERVICE_PROVIDER_VIEW_FAILED',
}
