.base-buildx-bake:
  stage: 'Build Back'
  image: ${FC_DOCKER_REGISTRY}/ci-cd-slim:latest
  services:
    - name: docker:28-dind
      alias: docker
      command: ['--storage-driver=overlay2']
  tags:
    - build-fc-nubo

  allow_failure: true

  rules:
    - if: '$CI_COMMIT_TAG'
      when: manual
    - when: never

  environment:
    name: build

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ''
    RELEASE_VERSION: ${CI_COMMIT_REF_NAME}
    PROXY_EXPLOITATION: ${HTTPS_PROXY}
    INTERNET_PROXY: ${PROXY_EXPLOITATION}
    APP_VERSION: ${CI_COMMIT_REF_NAME}

  before_script:
    - export PATH="${PATH}:${FC_ROOT}/fc/tools/bin"
    - echo "$CI_DEPENDENCY_PROXY_PASSWORD" | docker login "$CI_DEPENDENCY_PROXY_SERVER" -u "$CI_DEPENDENCY_PROXY_USER" --password-stdin
    - echo $FC_DOCKER_REGISTRY_PASS | docker login -u $FC_DOCKER_REGISTRY_USER --password-stdin $FC_DOCKER_REGISTRY
  script:
    - docker-stack bake-nodejs-app $APP
    - echo -e "\e[1;34m$MSG $APP_VERSION\e[0m"

  interruptible: true
