import { toDataURL } from 'qrcode';

import { Test, TestingModule } from '@nestjs/testing';

import { QrcodeService } from './qrcode.service';

jest.mock('qrcode', () => ({
  toDataURL: jest.fn(),
}));

describe('QrcodeService', () => {
  let service: QrcodeService;

  const toDataURLMock = jest.mocked(toDataURL);

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [QrcodeService],
    }).compile();

    service = module.get<QrcodeService>(QrcodeService);
  });

  it('should be defined', () => {
    expect(service).toBeDefined();
  });

  describe('generateDataUrl', () => {
    // Given
    const data = 'https://example.com';
    const options = { size: 100 };
    const toDataURLMockedResult = Symbol('libResult');

    it('should generate a data url with qrcode library', async () => {
      // When
      await service.generateDataUrl(data, options);

      // Then
      expect(toDataURLMock).toHaveBeenCalledWith(data, options);
    });

    it('should return dataUrl generated by qrcode library', async () => {
      // Given
      toDataURLMock.mockResolvedValue(toDataURLMockedResult);

      // When
      const result = await service.generateDataUrl(data, options);

      // Then
      expect(result).toBe(toDataURLMockedResult);
    });
  });
});
