export const enum ErrorCode {
  JAR_FETCH = 1,
  INVALID_JAR = 2,
  MISSING_TRUSTED_JWKS = 3,
  INVALID_SIGNATURE = 4,
  INVALID_REQUEST_OBJECT_HEADER = 5,
  INVALID_REQUEST_OBJECT_PAYLOAD = 6,
  CLIENT_ID_MISMATCH = 7,
  JARM_ENCRYPTION = 8,
  MDOC_BUILD = 9,
  IDENTITY_NOT_FOUND = 10,
}
