export enum ActionTypes {
  PROCESS_VERIFIED_IDENTITY_FRAUD_CASE = 'PROCESS_VERIFIED_IDENTITY_FRAUD_CASE',
  PROCESS_UNVERIFIED_IDENTITY_FRAUD_CASE = 'PROCESS_UNVERIFIED_IDENTITY_FRAUD_CASE',
  GET_FRAUD_TRACKS = 'GET_FRAUD_TRACKS',
}
