/* istanbul ignore file */

// declarative file
export enum ServiceProviderEditActionTypes {
  SERVICE_PROVIDER_EDIT_REQUESTED = 'SERVICE_PROVIDER_EDIT_REQUESTED',
  SERVICE_PROVIDER_EDIT_SUCCESSED = 'SERVICE_PROVIDER_EDIT_SUCCESSED',
  SERVICE_PROVIDER_EDIT_FAILED = 'SERVICE_PROVIDER_EDIT_FAILED',
}
