/* istanbul ignore file */

// declarative file
export enum ServiceProvidersActionTypes {
  SERVICE_PROVIDERS_REQUESTED = 'SERVICE_PROVIDERS_REQUESTED',
  SERVICE_PROVIDERS_SUCCESSED = 'SERVICE_PROVIDERS_SUCCESSED',
  SERVICE_PROVIDERS_FAILED = 'SERVICE_PROVIDERS_FAILED',
}
