// == FI
const fia = {
  // -- FIA - FIA1-LOW - Activated
  "FIA1-LOW": {
    uid: "9c716f61-b8a1-435c-a407-ef4d677ec270",
    name: "fia1-low",
    active: true,
    display: true,
    isBeta: false,
    title: "Identity Provider 1 - eIDAS faible - ES256",
    image: "fi-mock-faible.svg",
    imageFocus: "fi-mock-faible.svg",
    alt: "impots",
    trustedIdentity: false,
    eidas: 1,
    mailto: "",
    featureHandlers: {
      coreVerify: "core-fca-default-verify",
      authenticationEmail: null,
      fcaAuthorizationUrl: "core-fca-default-authorization-url",
    },
    specificText: "specific text fia1-low",
    url: "https://fia1-low.docker.dev-franceconnect.fr/",
    statusURL: "https://fia1-low.docker.dev-franceconnect.fr/",
    discoveryUrl:
      "https://fia1-low.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    discovery: true,
    clientID: "myclientidforfia1-low",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    endSessionURL:
      "https://fia1-low.docker.dev-franceconnect.fr/user/session/end",
    response_types: ["code"],
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    redirect_uris: [
      "https://core-fca-low.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fca-low.docker.dev-franceconnect.fr/api/v2/client/logout-callback",
    ],
  },

  // -- FIA - FIA2-LOW - Activated
  "FIA2-LOW": {
    uid: "0e7c099f-fe86-49a0-b7d1-19df45397212",
    name: "fia2-low",
    active: true,
    display: true,
    isBeta: false,
    title: "Identity Provider 2 - eIDAS faible - RS256",
    image: "fi-mock-faible.svg",
    imageFocus: "fi-mock-faible.svg",
    alt: "impots",
    trustedIdentity: false,
    eidas: 1,
    mailto: "",
    featureHandlers: {
      coreVerify: "core-fca-default-verify",
      authenticationEmail: null,
      fcaAuthorizationUrl: "core-fca-default-authorization-url",
    },
    specificText: "specific text fia2-low",
    url: "https://fia2-low.docker.dev-franceconnect.fr/",
    statusURL: "https://fia2-low.docker.dev-franceconnect.fr/",
    discoveryUrl:
      "https://fia2-low.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    discovery: true,
    clientID: "myclientidforfia2-low",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    endSessionURL:
      "https://fia2-low.docker.dev-franceconnect.fr/user/session/end",
    response_types: ["code"],
    id_token_signed_response_alg: "RS256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "RS256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    redirect_uris: [
      "https://core-fca-low.docker.dev-franceconnect.fr/api/v2/oidc-callback/fia2-low",
    ],
    post_logout_redirect_uris: [
      "https://core-fca-low.docker.dev-franceconnect.fr/api/v2/client/logout-callback",
    ],
  },

  // -- FIA - FIA3-LOW - Deactivated but visible
  "FIA3-LOW": {
    uid: "405d3839-9182-415f-9926-597489d11509",
    name: "fia3-desactive-visible",
    active: false,
    display: true,
    isBeta: false,
    title: "Identity Provider 3 (désactivé)- eIDAS faible",
    image: "fi-mock-faible.svg",
    imageFocus: "fi-mock-faible.svg",
    alt: "impots",
    trustedIdentity: false,
    eidas: 1,
    mailto: "",
    featureHandlers: {
      coreVerify: "core-fca-default-verify",
      authenticationEmail: null,
      fcaAuthorizationUrl: "core-fca-default-authorization-url",
    },
    specificText: "specific text fia3-low",
    url: "https://fia3-low.docker.dev-franceconnect.fr/",
    statusURL: "https://fia3-low.docker.dev-franceconnect.fr/",
    discoveryUrl:
      "https://fia3-low.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    discovery: true,
    clientID: "myclientidforfia3-low",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    endSessionURL:
      "https://fia3-low.docker.dev-franceconnect.fr/user/session/end",
    response_types: ["code"],
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    redirect_uris: [
      "https://core-fca-low.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fca-low.docker.dev-franceconnect.fr/api/v2/client/logout-callback",
    ],
  },

  // -- FIA - FIA4-LOW - Activated - HS256
  "FIA4-LOW": {
    uid: "87762a76-7da0-442d-8243-5785f859b88b",
    name: "fia4-low",
    active: true,
    display: true,
    isBeta: false,
    title: "Identity Provider 4 - eIDAS faible - HS256",
    image: "fi-mock-faible.svg",
    imageFocus: "fi-mock-faible.svg",
    alt: "impots",
    trustedIdentity: false,
    eidas: 1,
    featureHandlers: {
      coreVerify: "core-fca-default-verify",
      authenticationEmail: null,
      fcaAuthorizationUrl: "core-fca-default-authorization-url",
    },
    mailto: "",
    specificText: "specific text fia4-low",
    url: "https://fia4-low.docker.dev-franceconnect.fr/",
    statusURL: "https://fia4-low.docker.dev-franceconnect.fr/",
    discoveryUrl:
      "https://fia4-low.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    discovery: true,
    clientID: "myclientidforfia4-low",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    endSessionURL:
      "https://fia4-low.docker.dev-franceconnect.fr/user/session/end",
    response_types: ["code"],
    id_token_signed_response_alg: "HS256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "HS256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    redirect_uris: [
      "https://core-fca-low.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fca-low.docker.dev-franceconnect.fr/api/v2/client/logout-callback",
    ],
  },

  // -- FIA - FIA5-LOW - activated - RS256
  "FIA5-LOW": {
    uid: "46f5d9f9-881d-46b1-bdcc-0548913ea443",
    name: "fia5-low",
    active: true,
    display: true,
    isBeta: false,
    title: "Identity Provider 5 - eIDAS faible - RS256",
    image: "fi-mock-faible.svg",
    imageFocus: "fi-mock-faible.svg",
    alt: "impots",
    trustedIdentity: false,
    eidas: 1,
    featureHandlers: {
      coreVerify: "core-fca-default-verify",
      authenticationEmail: null,
      fcaAuthorizationUrl: "core-fca-default-authorization-url",
    },
    mailto: "",
    specificText: "specific text fia5-low",
    url: "https://fia5-low.docker.dev-franceconnect.fr/",
    statusURL: "https://fia5-low.docker.dev-franceconnect.fr/",
    discoveryUrl:
      "https://fia5-low.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    discovery: true,
    clientID: "myclientidforfia5-low",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    endSessionURL:
      "https://fia5-low.docker.dev-franceconnect.fr/user/session/end",
    response_types: ["code"],
    id_token_signed_response_alg: "RS256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "RS256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    redirect_uris: [
      "https://core-fca-low.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fca-low.docker.dev-franceconnect.fr/api/v2/client/logout-callback",
    ],
  },

  // -- FIA - FIA6-LOW - Activated but not visible
  "FIA6-LOW": {
    uid: "ccae1186-3695-4ae2-8b38-d3a9926d92c4",
    name: "fia6-active-invisible",
    active: true,
    display: false,
    isBeta: false,
    title: "Identity Provider 6 (non visible)- eIDAS faible",
    image: "fi-mock-faible.svg",
    imageFocus: "fi-mock-faible.svg",
    alt: "impots",
    trustedIdentity: false,
    eidas: 1,
    mailto: "",
    featureHandlers: {
      coreVerify: "core-fca-default-verify",
      authenticationEmail: null,
      fcaAuthorizationUrl: "core-fca-default-authorization-url",
    },
    specificText: "specific text fia6-low",
    url: "https://fia6-low.docker.dev-franceconnect.fr/",
    statusURL: "https://fia6-low.docker.dev-franceconnect.fr/",
    discoveryUrl:
      "https://fia6-low.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    discovery: true,
    clientID: "myclientidforfia3-low",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    endSessionURL:
      "https://fia6-low.docker.dev-franceconnect.fr/user/session/end",
    response_types: ["code"],
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    redirect_uris: [
      "https://core-fca-low.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fca-low.docker.dev-franceconnect.fr/api/v2/client/logout-callback",
    ],
  },

  // -- FIA - FIA7-LOW - Deactivated and not visible
  "FIA7-LOW": {
    uid: "b61f31b8-c131-40d0-9eca-109219249db6",
    name: "fia7-desactive-invisible",
    active: false,
    display: false,
    isBeta: false,
    title: "Identity Provider 7 (désactivé et non visible)- eIDAS faible",
    image: "fi-mock-faible.svg",
    imageFocus: "fi-mock-faible.svg",
    alt: "impots",
    trustedIdentity: false,
    eidas: 1,
    mailto: "",
    featureHandlers: {
      coreVerify: "core-fca-default-verify",
      authenticationEmail: null,
      fcaAuthorizationUrl: "core-fca-default-authorization-url",
    },
    specificText: "specific text fia7-low",
    url: "https://fia7-low.docker.dev-franceconnect.fr/",
    statusURL: "https://fia7-low.docker.dev-franceconnect.fr/",
    discoveryUrl:
      "https://fia7-low.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    discovery: true,
    clientID: "myclientidforfia3-low",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    endSessionURL:
      "https://fia7-low.docker.dev-franceconnect.fr/user/session/end",
    response_types: ["code"],
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    redirect_uris: [
      "https://core-fca-low.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fca-low.docker.dev-franceconnect.fr/api/v2/client/logout-callback",
    ],
  },

  // -- FIA - FIA8-LOW - FSA5 ONLY
  "FIA8-LOW": {
    uid: "56c5831b-7749-4206-b961-11f840bc566b",
    name: "fia8-low",
    active: true,
    display: true,
    isBeta: false,
    title: "Identity Provider 8 (fsa5 seulement)- eIDAS faible",
    image: "fi-mock-faible.svg",
    imageFocus: "fi-mock-faible.svg",
    alt: "impots",
    trustedIdentity: false,
    eidas: 1,
    mailto: "",
    featureHandlers: {
      coreVerify: "core-fca-default-verify",
      authenticationEmail: null,
      fcaAuthorizationUrl: "core-fca-default-authorization-url",
    },
    specificText: "specific text fia1-low",
    url: "https://fia8-low.docker.dev-franceconnect.fr/",
    statusURL: "https://fia8-low.docker.dev-franceconnect.fr/",
    discoveryUrl:
      "https://fia8-low.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    discovery: true,
    clientID: "myclientidforfia8-low",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    endSessionURL:
      "https://fia8-low.docker.dev-franceconnect.fr/user/session/end",
    response_types: ["code"],
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    redirect_uris: [
      "https://core-fca-low.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fca-low.docker.dev-franceconnect.fr/api/v2/client/logout-callback",
    ],
  },

  // -- FIA - MonComptePro - Activated
  "MONCOMPTEPRO": {
    uid: "71144ab3-ee1a-4401-b7b3-79b44f7daeeb",
    name: "moncomptepro",
    active: true,
    display: true,
    isBeta: false,
    title: "Identity Provider MonComptePro",
    image: "fi-mock-faible.svg",
    imageFocus: "fi-mock-faible.svg",
    alt: "moncomptepro ",
    trustedIdentity: false,
    eidas: 1,
    mailto: "",
    featureHandlers: {
      coreVerify: "core-fca-mcp-verify",
      authenticationEmail: null,
      fcaAuthorizationUrl: "core-fca-mcp-authorization-url",
    },
    specificText: "specific text MonComptePro",
    url: "https://moncomptepro.docker.dev-franceconnect.fr",
    discoveryUrl:
      "https://moncomptepro.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    discovery: true,
    clientID: "myclientidformoncomptepro",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    endSessionURL:
      "https://moncomptepro.docker.dev-franceconnect.fr/user/session/end",
    response_types: ["code"],
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    redirect_uris: [
      "https://core-fca-low.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fca-low.docker.dev-franceconnect.fr/api/v2/client/logout-callback",
    ],
  },
  // RIE

  // -- FIA - FIA-RIE-LOW - Activated
  "FIA-RIE-LOW": {
    uid: "c6ecab5e-dc67-4390-af57-fe208e97b649",
    name: "fia-rie-low",
    active: true,
    display: true,
    isBeta: false,
    title: "Identity Provider RIE - eIDAS faible - ES256",
    image: "fi-mock-faible.svg",
    imageFocus: "fi-mock-faible.svg",
    alt: "impots",
    trustedIdentity: false,
    eidas: 1,
    mailto: "",
    featureHandlers: {
      coreVerify: "core-fca-default-verify",
      authenticationEmail: null,
      fcaAuthorizationUrl: "core-fca-default-authorization-url",
    },
    specificText: "specific text fia-rie-low",
    url: "https://fia-rie-low.docker.dev-franceconnect.fr/",
    statusURL: "https://fia-rie-low.docker.dev-franceconnect.fr/",
    discoveryUrl:
      "https://fia-rie-low.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    discovery: true,
    clientID: "myclientidforfia-rie-low",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    endSessionURL:
      "https://fia-rie-low.docker.dev-franceconnect.fr/user/session/end",
    response_types: ["code"],
    id_token_signed_response_alg: "ES256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "",
    userinfo_signed_response_alg: "ES256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "",
    redirect_uris: [
      "https://core-fca-low.docker.dev-franceconnect.fr/api/v2/oidc-callback",
    ],
    post_logout_redirect_uris: [
      "https://core-fca-low.docker.dev-franceconnect.fr/api/v2/client/logout-callback",
    ],
  },

  // -- FIA using LemonLDAP
  "FIA-LLNG-LOW": {
    uid: "4be87184-1052-460b-9e14-3e164f584200",
    name: "LemonLDAP::ng",
    active: true,
    display: true,
    isBeta: false,
    title: "Identity Provider LemonLDAP",
    image: "fi-mock-eleve.svg",
    imageFocus: "fi-mock-eleve.svg",
    alt: "llng",
    trustedIdentity: false,
    eidas: 1,
    featureHandlers: {
      coreVerify: "core-fca-default-verify",
      authenticationEmail: null,
      fcaAuthorizationUrl: "core-fca-default-authorization-url",
    },
    mailto: "",
    specificText: "specific text llng",
    url: "https://auth.llng.docker.dev-franceconnect.fr",
    discoveryUrl:
      "https://auth.llng.docker.dev-franceconnect.fr/.well-known/openid-configuration",
    discovery: true,
    clientID: "myclientidforllng",
    client_secret:
      "jClItOnQiSZdE4kxm7EWzJbz4ckfD89k1e3NJw/pbGRHD/Jp6ooupqmHTyc3b62L9wqyF2TlR/5hJejE",
    order: null,
    updatedAt: new Date("2019-04-24 17:09:17"),
    updatedBy: "admin",
    endSessionURL:
      "https://auth.llng.docker.dev-franceconnect.fr/oauth2/logout",
    response_types: ["code"],
    id_token_signed_response_alg: "RS256",
    token_endpoint_auth_method: "client_secret_post",
    revocation_endpoint_auth_method: "client_secret_post",
    id_token_encrypted_response_alg: "",
    id_token_encrypted_response_enc: "A256GCM",
    userinfo_signed_response_alg: "RS256",
    userinfo_encrypted_response_alg: "",
    userinfo_encrypted_response_enc: "RS256",
    redirect_uris: [
      "https://core-fca-low.docker.dev-franceconnect.fr/api/v2/oidc-callback/fia-llng-low",
    ],
    post_logout_redirect_uris: [
      "https://core-fca-low.docker.dev-franceconnect.fr/api/v2/client/logout-callback",
    ],
  },
};

// -- Idps ----------
Object.values(fia).forEach((idp) => {
  print(`${idp.name} > Initializing provider: ${idp.name}`);
  db.provider.update({ name: idp.name }, idp, { upsert: true });
});
