export const enum CinematicEvents {
  DP_REQUESTED_FC_CHECKTOKEN = 'DP_REQUESTED_FC_CHECKTOKEN',
  FC_DATATRANSFER_CONSENT_IDENTITY = 'FC_DATATRANSFER_CONSENT_IDENTITY',
  FC_DATATRANSFER_CONSENT_DATA = 'FC_DATATRANSFER_CONSENT_DATA',
  FC_VERIFIED = 'FC_VERIFIED',
}
