#!/usr/bin/env bash

set -euo pipefail

APACHE_ENV_CONF="/etc/apache2/conf-enabled/znuny.conf"

VARS=(
  ZNUNY_UPDATE
  ZNUNY_UPGRADE
  ZNUNY_DB_HOST
  ZNUNY_DB_PORT
  ZNUNY_DB_NAME
  ZNUNY_DB_USER
  ZNUNY_DB_PASS
  ZNUNY_DB_SSLMODE
  ZNUNY_DB_SSLROOTCERT
  ZNUNY_DB_SSLCERT
  ZNUNY_DB_SSLKEY
)

echo "[init-znuny-env] Generating ${APACHE_ENV_CONF} …"

# Re create the file each time
{
  echo ""
  echo "# Autogenerated by init-znuny-env.sh"
  echo "<IfModule env_module>"

  for VAR in "${VARS[@]}"; do
    VALUE="${!VAR-}"
 
    if [[ -n "${VALUE}" ]]; then
      # Escape quotes
      ESCAPED_VALUE="${VALUE//\"/\\\"}"

      echo "    SetEnv ${VAR} \"${ESCAPED_VALUE}\""
      echo "[init-znuny-env] SetEnv ${VAR}" >&2
    else
      echo "[init-znuny-env] Ignored (not defined): ${VAR}" >&2
    fi
  done
  echo "</IfModule>"
} >> "${APACHE_ENV_CONF}" # Append to the existing file

echo "[init-znuny-env] Done."
 