export enum Openid4vpLogEvent {
  STATUS_SUBSCRIBE_FAILED = 'STATUS_SUBSCRIBE_FAILED',
  STATUS_SUBSCRIBER_ERROR = 'STATUS_SUBSCRIBER_ERROR',
  STATUS_MESSAGE_MALFORMED = 'STATUS_MESSAGE_MALFORMED',
  STATUS_PUBLISH_FAILED = 'STATUS_PUBLISH_FAILED',
}
