server {
  root /var/www;

  # "cache-busting-token" is a hard coded value for dev puprpose
  # Production value may change, while "/assets/" is permanently the base path.
  #
  # This path and the cache busting token must be made available for the app with 
  # environment variables :
  # - App_ASSETS_URL_PREFIX
  # - App_ASSETS_URL_DOMAIN
  location /assets/cache-busting-token {
    # Allow assets to be used from the core domain:
    add_header Access-Control-Allow-Origin https://core-fcp-low.docker.dev-franceconnect.fr;

    # Hide server informations 
    server_tokens off;

    # Allow clients to cache assets for a year
    add_header Cache-Control "public, max-age=31536000, immutable";

    alias /var/www/core-fcp-low/public;
  }
}
