import { Controller, Get, Header } from '@nestjs/common';

import { OidcClientRoutes, OidcClientService } from '@fc/oidc-client';

@Controller()
export class OidcClientController {
  constructor(private readonly oidcClient: OidcClientService) {}

  /**
   * @TODO #141 implement proper well-known
   * @see https://gitlab.dev-franceconnect.fr/france-connect/fc/-/issues/141
   *  - generated by openid-client
   *  - pub keys orverrided by keys from HSM
   */
  @Get(OidcClientRoutes.WELL_KNOWN_KEYS)
  @Header('cache-control', 'public, max-age=600')
  async getWellKnownKeys() {
    return await this.oidcClient.utils.wellKnownKeys();
  }
}
