export enum ErrorCode {
  DATAPASS_TRANSFORMATION_FAILED = 1,
  DATAPASS_VALIDATION_FAILED = 2,
  DATAPASS_NO_ACTIVE_AUTHORIZATION = 3,
  DATAPASS_EIDAS_LEVEL_FAILED = 4,
  DATAPASS_API_HTTP_FAILED = 5,
  DATAPASS_API_RESPONSE_VALIDATION_FAILED = 6,
  DATAPASS_PAGINATION_LIMIT_EXCEEDED = 7,
}
