export enum RnippResponseCodes {
  FOUND_NOT_RECTIFIED = '2',
  FOUND_RECTIFIED = '3',
  FOUND_ONLY_WITH_MARITAL_NAME = '7',
  NOT_FOUND_SINGLE_ECHO = '4',
  NOT_FOUND_MULTIPLE_ECHO = '6',
  NOT_FOUND_NO_ECHO = '8',
  REJECTED_BAD_REQUEST = '9',
}
