/* istanbul ignore file */

// Declarative code
export enum PermissionsType {
  SERVICE_PROVIDER_LIST = 'SERVICE_PROVIDER_LIST',
  SERVICE_PROVIDER_VIEW = 'SERVICE_PROVIDER_VIEW',
  SERVICE_PROVIDER_EDIT = 'SERVICE_PROVIDER_EDIT',
  SERVICE_PROVIDER_CONFIGURATION_CREATE = 'SERVICE_PROVIDER_CONFIGURATION_CREATE',
  SERVICE_PROVIDER_CONFIGURATION_LIST = 'SERVICE_PROVIDER_CONFIGURATION_LIST',
}
